/**
 * Fuente de verdad de proyectos, secciones y entidades (espejo de SQL 008/009).
 * Si PG está vacío, se usa para bootstrap; luego prima lab.entity_definition.
 */
import type { EntityDefinitionRecord, StoreProjectRecord, StoreSectionRecord } from "./catalog-types.js";

export const STORE_PROJECTS: StoreProjectRecord[] = [
	{
		slug: "isa-doc",
		name: "ISA-DOC",
		description: "Documentación, tickets, bitácora y datos editoriales del front estático.",
		sort_key: 10,
	},
	{
		slug: "patyia",
		name: "PatyIA",
		description: "Asistente IA: conversaciones, prompts, caches y catálogo API.",
		sort_key: 20,
	},
	{
		slug: "clientesis",
		name: "ClientesIS · ContaPymeU",
		description: "Capacitación ContaPymeU y snapshots Postman para gh-pages.",
		sort_key: 30,
	},
];

export const STORE_SECTIONS: StoreSectionRecord[] = [
	{ project_slug: "isa-doc", slug: "tickets", name: "Tickets", sort_key: 10 },
	{ project_slug: "isa-doc", slug: "postman", name: "Postman / API", sort_key: 20 },
	{ project_slug: "isa-doc", slug: "bitacora", name: "Bitácora", sort_key: 30 },
	{ project_slug: "isa-doc", slug: "patyia", name: "PatyIA (datos)", sort_key: 40 },
	{ project_slug: "isa-doc", slug: "openai", name: "OpenAI storage", sort_key: 50 },
	{ project_slug: "isa-doc", slug: "clientesis-schema", name: "Esquema ClientesIS", sort_key: 60 },
	{ project_slug: "isa-doc", slug: "codegen", name: "Codegen DER", sort_key: 70 },
	{ project_slug: "patyia", slug: "api", name: "Catálogo API", sort_key: 10 },
	{ project_slug: "patyia", slug: "prompts", name: "Prompts", sort_key: 20 },
	{ project_slug: "patyia", slug: "caches", name: "Caches", sort_key: 30 },
	{ project_slug: "patyia", slug: "postman-catalog", name: "Postman (UI)", sort_key: 40 },
	{ project_slug: "patyia", slug: "bitacora", name: "Bitácora", sort_key: 50 },
	{ project_slug: "clientesis", slug: "capacitacion", name: "Capacitación", sort_key: 10 },
	{ project_slug: "clientesis", slug: "postman-catalog", name: "Postman (UI)", sort_key: 20 },
	{ project_slug: "clientesis", slug: "bitacora", name: "Bitácora", sort_key: 30 },
];

const CAP = "clientesis";
const CAP_PAGE = "capacitacion";

function col(
	name: string,
	kind: "string" | "number" | "boolean" | "json" = "string",
	opts?: { required?: boolean },
) {
	return { name, kind, ...opts };
}

export const ENTITY_DEFINITIONS: EntityDefinitionRecord[] = [
	// --- isa-doc ---
	{
		project_slug: "isa-doc",
		section_slug: "tickets",
		entity_slug: "ticket",
		name: "Ticket",
		primary_keys: ["ITICKET"],
		columns: [
			col("ITICKET", "string", { required: true }),
			col("titulo"),
			col("solicitante"),
			col("fechaSolicitud"),
			col("fechaEntrega"),
			col("resumen"),
			col("estado"),
			col("proyecto"),
			col("pagina"),
			col("bodyModule"),
			col("sqlModule"),
			col("normativa", "json"),
			col("commits", "json"),
			col("cambiosBd", "json"),
			col("meta", "json"),
		],
		search_fields: ["ITICKET", "titulo", "solicitante", "resumen"],
		details: [
			{
				key: "assets",
				child: { project: "isa-doc", page: "tickets", entity: "imgbb-asset" },
				fk: { ITICKET: "ITICKET" },
				cascadeDelete: true,
			},
		],
		sort_key: 10,
	},
	{
		project_slug: "isa-doc",
		section_slug: "tickets",
		entity_slug: "imgbb-asset",
		name: "Asset imgbb",
		primary_keys: ["IIMGBB"],
		columns: [
			col("IIMGBB", "string", { required: true }),
			col("ITICKET"),
			col("kind"),
			col("mermaidSource"),
			col("mermaidInkUrl"),
			col("sourceSha1"),
			col("sha1"),
			col("url"),
			col("display_url"),
			col("thumb"),
			col("width", "number"),
			col("height", "number"),
			col("size", "number"),
			col("publishedAt"),
		],
		search_fields: ["IIMGBB", "ITICKET", "mermaidInkUrl", "sourceSha1"],
		sort_key: 20,
	},
	{
		project_slug: "isa-doc",
		section_slug: "postman",
		entity_slug: "endpoint",
		name: "Endpoint API",
		primary_keys: ["IAPIPROJECT", "IENDPOINT"],
		columns: [
			col("IAPIPROJECT", "string", { required: true }),
			col("IENDPOINT", "string", { required: true }),
			col("name"),
			col("method"),
			col("path"),
			col("folder"),
			col("tags", "json"),
			col("body", "json"),
			col("overrides", "json"),
		],
		search_fields: ["name", "path", "IAPIPROJECT"],
		sort_key: 10,
	},
	{
		project_slug: "isa-doc",
		section_slug: "bitacora",
		entity_slug: "revisado",
		name: "Revisado bitácora",
		primary_keys: ["IREVISADOKEY"],
		columns: [col("IREVISADOKEY", "string", { required: true }), col("revisado", "boolean"), col("proyecto"), col("pagina")],
		search_fields: ["IREVISADOKEY"],
		sort_key: 10,
	},
	{
		project_slug: "isa-doc",
		section_slug: "patyia",
		entity_slug: "prompt",
		name: "Prompt PatyIA",
		primary_keys: ["IPROMPTPATH"],
		columns: [col("IPROMPTPATH", "string", { required: true }), col("title"), col("body"), col("tags", "json")],
		search_fields: ["IPROMPTPATH", "title"],
		sort_key: 10,
	},
	{
		project_slug: "isa-doc",
		section_slug: "openai",
		entity_slug: "file-meta",
		name: "Metadato archivo OpenAI",
		primary_keys: ["IOAIFILEID"],
		columns: [col("IOAIFILEID", "string", { required: true }), col("filename"), col("purpose"), col("meta", "json")],
		sort_key: 10,
	},
	{
		project_slug: "isa-doc",
		section_slug: "clientesis-schema",
		entity_slug: "table",
		name: "Tabla DER",
		primary_keys: ["ITABLEID"],
		columns: [col("ITABLEID", "string", { required: true }), col("tableref"), col("rowname"), col("columns", "json")],
		search_fields: ["tableref", "rowname"],
		sort_key: 10,
	},
	{
		project_slug: "isa-doc",
		section_slug: "codegen",
		entity_slug: "state",
		name: "Estado codegen",
		primary_keys: ["ICODEGENSTATE"],
		columns: [col("ICODEGENSTATE", "string", { required: true }), col("body", "json")],
		sort_key: 10,
	},
	// --- patyia ---
	{
		project_slug: "patyia",
		section_slug: "bitacora",
		entity_slug: "layout",
		name: "Bitácora layout",
		primary_keys: ["ILAYOUTID"],
		columns: [col("ILAYOUTID", "string", { required: true }), col("version", "number"), col("nodes", "json")],
		sort_key: 5,
	},
	{
		project_slug: "patyia",
		section_slug: "bitacora",
		entity_slug: "segment-md",
		name: "Bitácora segmento MD",
		primary_keys: ["ISEGMENTID"],
		columns: [
			col("ISEGMENTID", "string", { required: true }),
			col("markdown"),
			col("sourcePath"),
			col("dayId"),
		],
		search_fields: ["ISEGMENTID", "dayId"],
		sort_key: 10,
	},
	{
		project_slug: "patyia",
		section_slug: "bitacora",
		entity_slug: "segment-sql",
		name: "Bitácora segmento SQL",
		primary_keys: ["ISEGMENTID"],
		columns: [
			col("ISEGMENTID", "string", { required: true }),
			col("title"),
			col("sql"),
			col("desc"),
			col("checkKey"),
			col("confirmKind"),
			col("confirmMessage"),
			col("height"),
			col("dbTarget"),
		],
		search_fields: ["ISEGMENTID", "checkKey", "title"],
		sort_key: 20,
	},
	{
		project_slug: "clientesis",
		section_slug: "bitacora",
		entity_slug: "layout",
		name: "Bitácora layout",
		primary_keys: ["ILAYOUTID"],
		columns: [col("ILAYOUTID", "string", { required: true }), col("version", "number"), col("nodes", "json")],
		sort_key: 5,
	},
	{
		project_slug: "clientesis",
		section_slug: "bitacora",
		entity_slug: "segment-md",
		name: "Bitácora segmento MD",
		primary_keys: ["ISEGMENTID"],
		columns: [
			col("ISEGMENTID", "string", { required: true }),
			col("markdown"),
			col("sourcePath"),
			col("dayId"),
		],
		search_fields: ["ISEGMENTID", "dayId"],
		sort_key: 10,
	},
	{
		project_slug: "clientesis",
		section_slug: "bitacora",
		entity_slug: "segment-sql",
		name: "Bitácora segmento SQL",
		primary_keys: ["ISEGMENTID"],
		columns: [
			col("ISEGMENTID", "string", { required: true }),
			col("title"),
			col("sql"),
			col("desc"),
			col("checkKey"),
			col("confirmKind"),
			col("confirmMessage"),
			col("height"),
			col("dbTarget"),
		],
		search_fields: ["ISEGMENTID", "checkKey", "title"],
		sort_key: 20,
	},
	{
		project_slug: "patyia",
		section_slug: "api",
		entity_slug: "catalog-endpoint",
		name: "Endpoint catálogo",
		primary_keys: ["ICATALOGENDPOINT"],
		columns: [
			col("ICATALOGENDPOINT", "string", { required: true }),
			col("entity"),
			col("name"),
			col("method"),
			col("pathTemplate"),
			col("hostVar"),
			col("description"),
			col("bodyTemplate"),
			col("authBearer", "boolean"),
		],
		search_fields: ["name", "entity"],
		sort_key: 10,
	},
	{
		project_slug: "patyia",
		section_slug: "prompts",
		entity_slug: "prompt-file",
		name: "Archivo prompt",
		primary_keys: ["IPROMPTFILE"],
		columns: [col("IPROMPTFILE", "string", { required: true }), col("content"), col("hash")],
		sort_key: 10,
	},
	{
		project_slug: "patyia",
		section_slug: "caches",
		entity_slug: "conversaciones",
		name: "Cache conversaciones",
		primary_keys: ["ICONVCACHEID"],
		columns: [col("ICONVCACHEID", "string", { required: true }), col("body", "json")],
		sort_key: 10,
	},
	{
		project_slug: "patyia",
		section_slug: "caches",
		entity_slug: "identidades",
		name: "Cache identidades",
		primary_keys: ["IIDENTCACHEID"],
		columns: [col("IIDENTCACHEID", "string", { required: true }), col("body", "json")],
		sort_key: 20,
	},
	// --- clientesis capacitación ---
	{
		project_slug: CAP,
		section_slug: CAP_PAGE,
		entity_slug: "driver",
		name: "Driver",
		primary_keys: ["idriver"],
		columns: [
			col("idriver", "number", { required: true }),
			col("ndriver"),
			col("descripcion"),
			col("qniveles", "number"),
		],
		search_fields: ["ndriver"],
		details: [
			{
				key: "atributos",
				child: { project: CAP, page: CAP_PAGE, entity: "atributo-x-driver" },
				fk: { idriver: "idriver" },
				cascadeDelete: true,
			},
		],
		sort_key: 10,
	},
	{
		project_slug: CAP,
		section_slug: CAP_PAGE,
		entity_slug: "atributo-x-driver",
		name: "Atributo × Driver",
		primary_keys: ["idriver", "iatributo"],
		columns: [
			col("idriver", "number", { required: true }),
			col("iatributo", "number", { required: true }),
			col("qnivel", "number"),
			col("natributo"),
			col("tdatributo", "number"),
			col("brequerido", "boolean"),
			col("jconfig", "json"),
		],
		sort_key: 20,
	},
	{
		project_slug: CAP,
		section_slug: CAP_PAGE,
		entity_slug: "plan-estudio",
		name: "Plan de estudio",
		primary_keys: ["iplanestudio"],
		columns: [
			col("iplanestudio", "string", { required: true }),
			col("nombre"),
			col("descripcionplan"),
			col("ttdvisualizacion"),
			col("bgeneracertificados", "boolean"),
			col("bactivo", "boolean"),
		],
		search_fields: ["nombre", "iplanestudio"],
		details: [
			{
				key: "cursosdeplanestudio",
				child: { project: CAP, page: CAP_PAGE, entity: "curso-de-plan" },
				fk: { iplanestudio: "iplanestudio" },
				cascadeDelete: true,
			},
			{
				key: "prerrequisitos",
				child: { project: CAP, page: CAP_PAGE, entity: "curso-prerequisito" },
				fk: { iplanestudio: "iplanestudio" },
				cascadeDelete: true,
			},
		],
		sort_key: 30,
	},
	{
		project_slug: CAP,
		section_slug: CAP_PAGE,
		entity_slug: "curso-de-plan",
		name: "Curso de plan",
		primary_keys: ["iplanestudio", "icurso"],
		columns: [
			col("iplanestudio", "string", { required: true }),
			col("icurso", "string", { required: true }),
			col("qorden", "number"),
			col("brequerido", "boolean"),
			col("curso", "json"),
		],
		sort_key: 40,
	},
	{
		project_slug: CAP,
		section_slug: CAP_PAGE,
		entity_slug: "curso-prerequisito",
		name: "Prerrequisito curso",
		primary_keys: ["icurso", "icursorequerido", "iplanestudio"],
		columns: [
			col("icurso", "string", { required: true }),
			col("icursorequerido", "string", { required: true }),
			col("iplanestudio", "string", { required: true }),
		],
		sort_key: 50,
	},
	{
		project_slug: CAP,
		section_slug: CAP_PAGE,
		entity_slug: "curso",
		name: "Curso",
		primary_keys: ["icurso"],
		columns: [
			col("icurso", "string", { required: true }),
			col("ncurso"),
			col("itema"),
			col("idriver", "number"),
			col("descripcion"),
			col("bactivo", "boolean"),
			col("bgeneracertificado", "boolean"),
		],
		search_fields: ["icurso", "ncurso"],
		details: [
			{
				key: "seguridades",
				child: { project: CAP, page: CAP_PAGE, entity: "seguridad-curso" },
				fk: { icurso: "icurso" },
				cascadeDelete: true,
			},
			{
				key: "estructuras",
				child: { project: CAP, page: CAP_PAGE, entity: "estructura-curso" },
				fk: { icurso: "icurso" },
				cascadeDelete: true,
			},
			{
				key: "planescurso",
				child: { project: CAP, page: CAP_PAGE, entity: "plan-curso" },
				fk: { icurso: "icurso" },
			},
		],
		sort_key: 60,
	},
	{
		project_slug: CAP,
		section_slug: CAP_PAGE,
		entity_slug: "plan-curso",
		name: "Plan curso (árbol)",
		primary_keys: ["iplan", "icurso"],
		columns: [
			col("iplan", "string", { required: true }),
			col("icurso", "string", { required: true }),
			col("itema"),
			col("titulo"),
			col("irecurso", "number"),
			col("recurso", "json"),
			col("atributosplan", "json"),
		],
		sort_key: 70,
	},
	{
		project_slug: CAP,
		section_slug: CAP_PAGE,
		entity_slug: "atributos-plan",
		name: "Atributos plan",
		primary_keys: ["iatributo", "icurso", "iplan"],
		columns: [
			col("iatributo", "number", { required: true }),
			col("icurso", "string", { required: true }),
			col("iplan", "string", { required: true }),
			col("valor"),
		],
		sort_key: 80,
	},
	{
		project_slug: CAP,
		section_slug: CAP_PAGE,
		entity_slug: "seguridad-curso",
		name: "Seguridad curso",
		primary_keys: ["icurso", "ipermiso"],
		columns: [
			col("icurso", "string", { required: true }),
			col("ipermiso", "string", { required: true }),
			col("permiso", "json"),
		],
		sort_key: 90,
	},
	{
		project_slug: CAP,
		section_slug: CAP_PAGE,
		entity_slug: "estructura-curso",
		name: "Estructura curso",
		primary_keys: ["icurso", "qnivel"],
		columns: [
			col("icurso", "string", { required: true }),
			col("qnivel", "number", { required: true }),
			col("nnivel"),
		],
		sort_key: 100,
	},
	{
		project_slug: CAP,
		section_slug: CAP_PAGE,
		entity_slug: "permiso",
		name: "Permiso",
		primary_keys: ["ipermiso"],
		columns: [col("ipermiso", "string", { required: true }), col("npermiso")],
		search_fields: ["ipermiso", "npermiso"],
		sort_key: 110,
	},
	{
		project_slug: CAP,
		section_slug: CAP_PAGE,
		entity_slug: "tema",
		name: "Tema soporte",
		primary_keys: ["itema"],
		columns: [col("itema", "string", { required: true }), col("ntema")],
		sort_key: 120,
	},
	// Postman UI snapshots (gh-pages)
	...["cursos", "planes-de-estudio", "drivers", "permisos"].map((slug, i) => ({
		project_slug: CAP,
		section_slug: "postman-catalog",
		entity_slug: slug,
		name: slug.replace(/-/g, " "),
		primary_keys: ["ICATALOGSLUG"],
		columns: [col("ICATALOGSLUG", "string", { required: true }), col("name"), col("itemCount", "number"), col("payload", "json")],
		sort_key: 10 + i,
	})),
	...["conversacion", "jwt", "mensaje", "tiquete"].map((slug, i) => ({
		project_slug: "patyia",
		section_slug: "postman-catalog",
		entity_slug: slug,
		name: slug,
		primary_keys: ["ICATALOGSLUG"],
		columns: [col("ICATALOGSLUG", "string", { required: true }), col("name"), col("itemCount", "number"), col("payload", "json")],
		sort_key: 10 + i,
	})),
];
