/**
 * Nomenclatura PostgreSQL INSOFT / LangLab.
 *
 * - BD_LANGLAB: runtime LangLab (conversación, instrucción, orquestador, auth).
 * - BD_ISADOC: almacén ISA-DOC (entity row, tickets, revisado, catálogo Paty + ClientesIS).
 * - Tablas: dominio + sufijo solo si hay varias tablas del dominio (ej. CONVERSACION_TURNO).
 * - Columnas: MAYÚSCULAS sin _ (vía sqlCol en pg-quote.ts).
 */

import { pgQ, qualifiedQ, qualifiedSeq } from "./pg-quote.js";

export { pgQ, qualifiedQ, qualifiedSeq };

export const PG_SCHEMA_LANGLAB = "BD_LANGLAB";
/** Almacén PostgreSQL único de ISA-DOC (PatyIA + ClientesIS entity store, revisado, catálogo). */
export const PG_SCHEMA_ISADOC = "BD_ISADOC";
/** @deprecated Usar PG_SCHEMA_ISADOC */
export const PG_SCHEMA_PATY = PG_SCHEMA_ISADOC;
/** @deprecated Usar PG_SCHEMA_ISADOC */
export const PG_SCHEMA_CLIENTESIS = PG_SCHEMA_ISADOC;
/** @deprecated Usar PG_SCHEMA_ISADOC (store) o PG_SCHEMA_LANGLAB (runtime). */
export const PG_SCHEMA_LAB = PG_SCHEMA_ISADOC;
export const PG_SCHEMA_RAG = "BD_RAG";

/** @deprecated */
export const PG_SCHEMA_OPS = PG_SCHEMA_LANGLAB;

export function qualified(schema: string, table: string): string {
	return qualifiedQ(schema, table);
}

// --- Conversación (BD_LANGLAB) ---
export const T_CONVERSACION = "CONVERSACION";
export const T_CONVERSACION_TURNO = "CONVERSACION_TURNO";
export const T_CONVERSACION_MENSAJE = "CONVERSACION_MENSAJE";
export const T_CONVERSACION_MENSAJE_METRICAS = "CONVERSACION_MENSAJE_METRICAS";
/** @deprecated */
export const T_CONVERSACION_MENSAJECALIFICADO = T_CONVERSACION_MENSAJE;
export const T_CONVERSACION_TURNOLOCK = "CONVERSACION_TURNOLOCK";
export const T_CONVERSACION_TURNOTIMING = "CONVERSACION_TURNOTIMING";

export const Q_CONVERSACION = qualified(PG_SCHEMA_LANGLAB, T_CONVERSACION);
export const Q_CONVERSACION_TURNO = qualified(PG_SCHEMA_LANGLAB, T_CONVERSACION_TURNO);
export const Q_CONVERSACION_MENSAJE = qualified(PG_SCHEMA_LANGLAB, T_CONVERSACION_MENSAJE);
export const Q_CONVERSACION_MENSAJE_METRICAS = qualified(PG_SCHEMA_LANGLAB, T_CONVERSACION_MENSAJE_METRICAS);
/** @deprecated */
export const Q_CONVERSACION_MENSAJECALIFICADO = Q_CONVERSACION_MENSAJE;
export const Q_CONVERSACION_TURNOLOCK = qualified(PG_SCHEMA_LANGLAB, T_CONVERSACION_TURNOLOCK);
export const Q_CONVERSACION_TURNOTIMING = qualified(PG_SCHEMA_LANGLAB, T_CONVERSACION_TURNOTIMING);

// --- Instrucción / tipo consulta (BD_LANGLAB) ---
export const T_INSTRUCCION = "INSTRUCCION";
/** Catálogo tipo consulta: metadatos + instrucciones + corpus RAG (antes TDCONSULTA*). */
export const T_CONVERSACION_TIPOCONSULTA = "CONVERSACION_TIPOCONSULTA";

export const Q_INSTRUCCION = qualified(PG_SCHEMA_LANGLAB, T_INSTRUCCION);
export const Q_CONVERSACION_TIPOCONSULTA = qualified(PG_SCHEMA_LANGLAB, T_CONVERSACION_TIPOCONSULTA);

/** @deprecated Usar T_CONVERSACION_TIPOCONSULTA */
export const T_TDCONSULTA = T_CONVERSACION_TIPOCONSULTA;
/** @deprecated Tabla absorbida en CONVERSACION_TIPOCONSULTA.INSTRUCCIONES */
export const T_TDCONSULTA_INSTRUCCION = T_CONVERSACION_TIPOCONSULTA;
/** @deprecated Tabla absorbida en CONVERSACION_TIPOCONSULTA.CORPUS */
export const T_TDCONSULTA_CORPUS = T_CONVERSACION_TIPOCONSULTA;

/** @deprecated Usar Q_CONVERSACION_TIPOCONSULTA */
export const Q_TDCONSULTA = Q_CONVERSACION_TIPOCONSULTA;
/** @deprecated */
export const Q_TDCONSULTA_INSTRUCCION = Q_CONVERSACION_TIPOCONSULTA;
/** @deprecated */
export const Q_TDCONSULTA_CORPUS = Q_CONVERSACION_TIPOCONSULTA;

// --- Entity store / catálogo ISA-DOC (BD_ISADOC) ---
export const T_ENTITY_ROW = "ENTITY_ROW";
export const T_STORE_PROJECT = "STORE_PROJECT";
export const T_STORE_SECTION = "STORE_SECTION";
export const T_ENTITY_DEFINITION = "ENTITY_DEFINITION";
export const T_APICATALOG_MANIFEST = "APICATALOG_MANIFEST";
export const T_BITACORA_REVISADO = "BITACORA_REVISADO";
export const T_ORCHESTRATOR_SLOT = "ORCHESTRATOR_SLOT";
export const T_ORCHESTRATOR_LEASE = "ORCHESTRATOR_LEASE";
export const T_ORCHESTRATOR_CAPABILITY = "ORCHESTRATOR_CAPABILITY";
export const T_ORCHESTRATOR_ROTATIONLOG = "ORCHESTRATOR_ROTATIONLOG";
export const T_AUTH_USER = "AUTH_USER";
export const T_AUTH_ROLE = "AUTH_ROLE";
export const T_AUTH_ROLEALLOW = "AUTH_ROLEALLOW";
export const T_AUTH_USERALLOW = "AUTH_USERALLOW";

export const SEQ_STORE_PROJECT = "SEQ_STORE_PROJECT";
export const SEQ_STORE_SECTION = "SEQ_STORE_SECTION";
export const SEQ_ENTITY_DEFINITION = "SEQ_ENTITY_DEFINITION";

export const Q_ENTITY_ROW = qualified(PG_SCHEMA_ISADOC, T_ENTITY_ROW);
export const Q_STORE_PROJECT = qualified(PG_SCHEMA_ISADOC, T_STORE_PROJECT);
export const Q_STORE_SECTION = qualified(PG_SCHEMA_ISADOC, T_STORE_SECTION);
export const Q_ENTITY_DEFINITION = qualified(PG_SCHEMA_ISADOC, T_ENTITY_DEFINITION);
export const Q_APICATALOG_MANIFEST = qualified(PG_SCHEMA_ISADOC, T_APICATALOG_MANIFEST);
export const Q_BITACORA_REVISADO = qualified(PG_SCHEMA_ISADOC, T_BITACORA_REVISADO);

export const Q_ORCHESTRATOR_SLOT = qualified(PG_SCHEMA_LANGLAB, T_ORCHESTRATOR_SLOT);
export const Q_ORCHESTRATOR_LEASE = qualified(PG_SCHEMA_LANGLAB, T_ORCHESTRATOR_LEASE);
export const Q_ORCHESTRATOR_CAPABILITY = qualified(PG_SCHEMA_LANGLAB, T_ORCHESTRATOR_CAPABILITY);
export const Q_ORCHESTRATOR_ROTATIONLOG = qualified(PG_SCHEMA_LANGLAB, T_ORCHESTRATOR_ROTATIONLOG);
export const Q_AUTH_USER = qualified(PG_SCHEMA_LANGLAB, T_AUTH_USER);
export const Q_AUTH_ROLE = qualified(PG_SCHEMA_LANGLAB, T_AUTH_ROLE);
export const Q_AUTH_ROLEALLOW = qualified(PG_SCHEMA_LANGLAB, T_AUTH_ROLEALLOW);
export const Q_AUTH_USERALLOW = qualified(PG_SCHEMA_LANGLAB, T_AUTH_USERALLOW);

export const Q_SEQ_STORE_PROJECT = qualifiedSeq(PG_SCHEMA_ISADOC, SEQ_STORE_PROJECT);
export const Q_SEQ_STORE_SECTION = qualifiedSeq(PG_SCHEMA_ISADOC, SEQ_STORE_SECTION);
export const Q_SEQ_ENTITY_DEFINITION = qualifiedSeq(PG_SCHEMA_ISADOC, SEQ_ENTITY_DEFINITION);

// --- ClientesIS entity store (mismo esquema BD_ISADOC, proyecto lógico clientesis) ---
export const T_CLIENTESIS_ENTITY_ROW = "ENTITY_ROW";
export const Q_CLIENTESIS_ENTITY_ROW = Q_ENTITY_ROW;

// --- RAG ---
export const T_INDEX_RUN = "INDEX_RUN";
export const T_VECTOR_CONTAPYME = "VECTOR_CONTAPYME";

export const Q_INDEX_RUN = qualified(PG_SCHEMA_RAG, T_INDEX_RUN);
export const Q_VECTOR_CONTAPYME = qualified(PG_SCHEMA_RAG, T_VECTOR_CONTAPYME);

/** Columnas entity row (SQL quoted, sin _). */
export const COL_ER = {
	PROJECT: pgQ("PROJECT"),
	PAGE: pgQ("PAGE"),
	ENTITY: pgQ("ENTITY"),
	IENTITYID: pgQ("IENTITYID"),
	BODY: pgQ("BODY"),
	PARENTPROJECT: pgQ("PARENTPROJECT"),
	PARENTPAGE: pgQ("PARENTPAGE"),
	PARENTENTITY: pgQ("PARENTENTITY"),
	IPARENTENTITYID: pgQ("IPARENTENTITYID"),
	SORTKEY: pgQ("SORTKEY"),
	TAGS: pgQ("TAGS"),
	FHCRE: pgQ("FHCRE"),
	FHULTACT: pgQ("FHULTACT"),
} as const;

export const COL_ER_ALIASES = {
	PROJECT: "project",
	PAGE: "page",
	ENTITY: "entity",
	IENTITYID: "ientityid",
	BODY: "body",
	PARENTPROJECT: "parentproject",
	PARENTPAGE: "parentpage",
	PARENTENTITY: "parententity",
	IPARENTENTITYID: "iparententityid",
	SORTKEY: "sortkey",
	TAGS: "tags",
	FHCRE: "fhcre",
	FHULTACT: "fhultact",
} as const;

export function selectEntityRowCols(prefix = ""): string {
	const p = prefix ? `${prefix}.` : "";
	const a = COL_ER_ALIASES;
	return [
		`${p}${COL_ER.PROJECT} AS ${a.PROJECT}`,
		`${p}${COL_ER.PAGE} AS ${a.PAGE}`,
		`${p}${COL_ER.ENTITY} AS ${a.ENTITY}`,
		`${p}${COL_ER.IENTITYID} AS ${a.IENTITYID}`,
		`${p}${COL_ER.BODY} AS ${a.BODY}`,
		`${p}${COL_ER.PARENTPROJECT} AS ${a.PARENTPROJECT}`,
		`${p}${COL_ER.PARENTPAGE} AS ${a.PARENTPAGE}`,
		`${p}${COL_ER.PARENTENTITY} AS ${a.PARENTENTITY}`,
		`${p}${COL_ER.IPARENTENTITYID} AS ${a.IPARENTENTITYID}`,
		`${p}${COL_ER.SORTKEY} AS ${a.SORTKEY}`,
		`${p}${COL_ER.TAGS} AS ${a.TAGS}`,
		`${p}${COL_ER.FHCRE} AS ${a.FHCRE}`,
		`${p}${COL_ER.FHULTACT} AS ${a.FHULTACT}`,
	].join(", ");
}

export const COL_REV = {
	KEY: pgQ("REVISADOKEY"),
	BCHECKED: pgQ("BCHECKED"),
	FHULTACT: pgQ("FHULTACT"),
} as const;

export const COL_AUTH = {
	USERNAME: pgQ("USERNAME"),
	PASSWORDHASH: pgQ("PASSWORDHASH"),
	DISPLAYNAME: pgQ("DISPLAYNAME"),
	ROLECODE: pgQ("ROLECODE"),
	ACTIVE: pgQ("ACTIVE"),
	FHCRE: pgQ("FHCRE"),
	FHULTACT: pgQ("FHULTACT"),
} as const;

export const COL_AUTH_ROLE = {
	ROLECODE: pgQ("ROLECODE"),
	DESCRIPTION: pgQ("DESCRIPTION"),
	ACTIVE: pgQ("ACTIVE"),
	FHCRE: pgQ("FHCRE"),
	FHULTACT: pgQ("FHULTACT"),
} as const;

export const COL_AUTH_ROLEALLOW = {
	ROLECODE: pgQ("ROLECODE"),
	ALLOWRULE: pgQ("ALLOWRULE"),
} as const;

export const COL_AUTH_USERALLOW = {
	USERNAME: pgQ("USERNAME"),
	ALLOWRULE: pgQ("ALLOWRULE"),
	SQLSCOPE: pgQ("SQLSCOPE"),
	DESCRIPTION: pgQ("DESCRIPTION"),
} as const;

export const COL_ER_PK = COL_ER.IENTITYID;

// --- Alias legacy (migraciones / código antiguo) ---
export const T_CONVERSACION_CONVERSACION = T_CONVERSACION;
export const T_CONVERSACION_CONVERSACIONTURNO = T_CONVERSACION_TURNO;
export const T_INSTRUCCION_INSTRUCCION = T_INSTRUCCION;
export const T_TDCONSULTA_TDCONSULTA = T_TDCONSULTA;
export const T_ENTITY_ENTITYROW = T_ENTITY_ROW;
export const T_CLIENTESIS_ENTITYROW = T_CLIENTESIS_ENTITY_ROW;

export const Q_CONVERSACION_CONVERSACION = Q_CONVERSACION;
export const Q_CONVERSACION_CONVERSACIONTURNO = Q_CONVERSACION_TURNO;
export const Q_CONVERSACION_CONVERSACIONTURNOLOCK = Q_CONVERSACION_TURNOLOCK;
export const Q_CONVERSACION_CONVERSACIONTURNOTIMING = Q_CONVERSACION_TURNOTIMING;
export const Q_INSTRUCCION_INSTRUCCION = Q_INSTRUCCION;
export const Q_TDCONSULTA_TDCONSULTA = Q_TDCONSULTA;
export const Q_TDCONSULTA_TDCONSULTAINSTRUCCION = Q_TDCONSULTA_INSTRUCCION;
export const Q_TDCONSULTA_TDCONSULTACORPUS = Q_TDCONSULTA_CORPUS;
export const Q_ENTITY_ENTITYROW = Q_ENTITY_ROW;

export const Q_PATY_CONVERSACION = Q_CONVERSACION;
export const Q_PATY_CONVERSACIONTURNO = Q_CONVERSACION_TURNO;
export const Q_PATY_MENSAJE = Q_CONVERSACION_MENSAJE;
export const Q_PATY_MENSAJE_METRICAS = Q_CONVERSACION_MENSAJE_METRICAS;
export const Q_PATY_MENSAJECALIFICADO = Q_CONVERSACION_MENSAJE;
export const Q_PATY_CONVERSACIONTURNOLOCK = Q_CONVERSACION_TURNOLOCK;
export const Q_PATY_CONVERSACIONTURNOTIMING = Q_CONVERSACION_TURNOTIMING;
export const Q_PATY_INSTRUCCION = Q_INSTRUCCION;
export const Q_PATY_TDCONSULTA = Q_CONVERSACION_TIPOCONSULTA;
export const Q_PATY_TDCONSULTAINSTRUCCION = Q_CONVERSACION_TIPOCONSULTA;
export const Q_PATY_TDCONSULTACORPUS = Q_CONVERSACION_TIPOCONSULTA;
export const Q_PATY_CONVERSACION_TIPOCONSULTA = Q_CONVERSACION_TIPOCONSULTA;
export const Q_PATY_CONVERSACION_TURNO = Q_CONVERSACION_TURNO;
export const Q_PATY_MENSAJE_CALIFICADO = Q_CONVERSACION_MENSAJE;
export const Q_PATY_CONVERSACION_TURNO_LOCK = Q_CONVERSACION_TURNOLOCK;
export const Q_PATY_CONVERSACION_TURNO_TIMING = Q_CONVERSACION_TURNOTIMING;
export const Q_PATY_TDCONSULTA_INSTRUCCION = Q_CONVERSACION_TIPOCONSULTA;
export const Q_PATY_TDCONSULTA_CORPUS = Q_CONVERSACION_TIPOCONSULTA;

export const Q_LAB_ENTITY_ROW = Q_ENTITY_ROW;
export const Q_LAB_STORE_PROJECT = Q_STORE_PROJECT;
export const Q_LAB_STORE_SECTION = Q_STORE_SECTION;
export const Q_LAB_ENTITY_DEFINITION = Q_ENTITY_DEFINITION;
export const Q_LAB_API_CATALOG_MANIFEST = Q_APICATALOG_MANIFEST;
export const Q_LAB_BITACORA_REVISADO = Q_BITACORA_REVISADO;
export const Q_LAB_API_KEY_SLOT = Q_ORCHESTRATOR_SLOT;
export const Q_LAB_ORCHESTRATOR_LEASE = Q_ORCHESTRATOR_LEASE;
export const Q_LAB_CAPABILITY_TIMING = Q_ORCHESTRATOR_CAPABILITY;
export const Q_LAB_ORCHESTRATOR_ROTATION_LOG = Q_ORCHESTRATOR_ROTATIONLOG;
export const Q_LAB_AUTH_USER = Q_AUTH_USER;

export const T_LAB_ENTITY_ROW = T_ENTITY_ROW;
export const T_LAB_API_KEY_SLOT = T_ORCHESTRATOR_SLOT;
export const T_LAB_ORCHESTRATOR_LEASE = T_ORCHESTRATOR_LEASE;
export const T_LAB_CAPABILITY_TIMING = T_ORCHESTRATOR_CAPABILITY;
export const T_LAB_ORCHESTRATOR_ROTATION_LOG = T_ORCHESTRATOR_ROTATIONLOG;
export const T_PATY_CONVERSACION_TURNO_LOCK = T_CONVERSACION_TURNOLOCK;
export const T_PATY_CONVERSACION_TURNO_TIMING = T_CONVERSACION_TURNOTIMING;
export const T_RAG_VEC_CONTAPYME = T_VECTOR_CONTAPYME;
export const Q_CIS_ENTITY_ROW = Q_CLIENTESIS_ENTITY_ROW;
export const T_CIS_ENTITY_ROW = T_CLIENTESIS_ENTITY_ROW;
export const Q_RAG_INDEX_RUN = Q_INDEX_RUN;
export const Q_RAG_VEC_CONTAPYME = Q_VECTOR_CONTAPYME;
