/**
 * Nomenclatura PostgreSQL INSOFT / ispgen.
 *
 * - Esquemas: BD_PATY, BD_LAB, BD_CLIENTESIS, BD_RAG (dominio producto / proyecto)
 * - Tablas: PREFIJO_ENTIDAD + nombre (dominio de la entidad principal, NO el esquema)
 *   Ej. CONVERSACION_CONVERSACION, ENTITY_ENTITYROW, TDCONSULTA_TDCONSULTA
 * - Columnas: mayúsculas, sin guion bajo; ids con I; fechas fhcre/fhultact; booleanos b*
 */

import { pgQ, qualifiedQ, qualifiedSeq } from "./pg-quote.js";

export { pgQ, qualifiedQ, qualifiedSeq };

/** Esquema (= proyecto / producto lógico). */
export const PG_SCHEMA_PATY = "BD_PATY";
export const PG_SCHEMA_LAB = "BD_LAB";
export const PG_SCHEMA_CLIENTESIS = "BD_CLIENTESIS";
export const PG_SCHEMA_RAG = "BD_RAG";

/** @deprecated Usar PG_SCHEMA_* */
export const PG_SCHEMA_OPS = PG_SCHEMA_PATY;

export function qualified(schema: string, table: string): string {
	return qualifiedQ(schema, table);
}

// --- Conversación (BD_PATY) ---
export const T_CONVERSACION_CONVERSACION = "CONVERSACION_CONVERSACION";
export const T_CONVERSACION_CONVERSACIONTURNO = "CONVERSACION_CONVERSACIONTURNO";
export const T_CONVERSACION_MENSAJECALIFICADO = "CONVERSACION_MENSAJECALIFICADO";
export const T_CONVERSACION_CONVERSACIONTURNOLOCK = "CONVERSACION_CONVERSACIONTURNOLOCK";
export const T_CONVERSACION_CONVERSACIONTURNOTIMING = "CONVERSACION_CONVERSACIONTURNOTIMING";

export const Q_CONVERSACION_CONVERSACION = qualified(PG_SCHEMA_PATY, T_CONVERSACION_CONVERSACION);
export const Q_CONVERSACION_CONVERSACIONTURNO = qualified(PG_SCHEMA_PATY, T_CONVERSACION_CONVERSACIONTURNO);
export const Q_CONVERSACION_MENSAJECALIFICADO = qualified(PG_SCHEMA_PATY, T_CONVERSACION_MENSAJECALIFICADO);
export const Q_CONVERSACION_CONVERSACIONTURNOLOCK = qualified(PG_SCHEMA_PATY, T_CONVERSACION_CONVERSACIONTURNOLOCK);
export const Q_CONVERSACION_CONVERSACIONTURNOTIMING = qualified(PG_SCHEMA_PATY, T_CONVERSACION_CONVERSACIONTURNOTIMING);

// --- Instrucción / tipo consulta (BD_PATY) ---
export const T_INSTRUCCION_INSTRUCCION = "INSTRUCCION_INSTRUCCION";
export const T_TDCONSULTA_TDCONSULTA = "TDCONSULTA_TDCONSULTA";
export const T_TDCONSULTA_TDCONSULTAINSTRUCCION = "TDCONSULTA_TDCONSULTAINSTRUCCION";
export const T_TDCONSULTA_TDCONSULTACORPUS = "TDCONSULTA_TDCONSULTACORPUS";

export const Q_INSTRUCCION_INSTRUCCION = qualified(PG_SCHEMA_PATY, T_INSTRUCCION_INSTRUCCION);
export const Q_TDCONSULTA_TDCONSULTA = qualified(PG_SCHEMA_PATY, T_TDCONSULTA_TDCONSULTA);
export const Q_TDCONSULTA_TDCONSULTAINSTRUCCION = qualified(PG_SCHEMA_PATY, T_TDCONSULTA_TDCONSULTAINSTRUCCION);
export const Q_TDCONSULTA_TDCONSULTACORPUS = qualified(PG_SCHEMA_PATY, T_TDCONSULTA_TDCONSULTACORPUS);

// --- Entity store / catálogo (BD_LAB) ---
export const T_ENTITY_ENTITYROW = "ENTITY_ENTITYROW";
export const T_STORE_STOREPROJECT = "STORE_STOREPROJECT";
export const T_STORE_STORESECTION = "STORE_STORESECTION";
export const T_ENTITY_ENTITYDEFINITION = "ENTITY_ENTITYDEFINITION";
export const T_APICATALOG_APICATALOGMANIFEST = "APICATALOG_APICATALOGMANIFEST";
export const T_BITACORA_BITACORAREVISADO = "BITACORA_BITACORAREVISADO";
export const T_ORCHESTRATOR_APIKEYSLOT = "ORCHESTRATOR_APIKEYSLOT";
export const T_ORCHESTRATOR_ORCHESTRATORLEASE = "ORCHESTRATOR_ORCHESTRATORLEASE";
export const T_ORCHESTRATOR_CAPABILITYTIMING = "ORCHESTRATOR_CAPABILITYTIMING";
export const T_ORCHESTRATOR_ORCHESTRATORROTATIONLOG = "ORCHESTRATOR_ORCHESTRATORROTATIONLOG";
export const T_AUTH_AUTHUSER = "AUTH_AUTHUSER";

export const SEQ_STORE_STOREPROJECT = "SEQ_STORE_STOREPROJECT";
export const SEQ_STORE_STORESECTION = "SEQ_STORE_STORESECTION";
export const SEQ_ENTITY_ENTITYDEFINITION = "SEQ_ENTITY_ENTITYDEFINITION";

export const Q_ENTITY_ENTITYROW = qualified(PG_SCHEMA_LAB, T_ENTITY_ENTITYROW);
export const Q_STORE_STOREPROJECT = qualified(PG_SCHEMA_LAB, T_STORE_STOREPROJECT);
export const Q_STORE_STORESECTION = qualified(PG_SCHEMA_LAB, T_STORE_STORESECTION);
export const Q_ENTITY_ENTITYDEFINITION = qualified(PG_SCHEMA_LAB, T_ENTITY_ENTITYDEFINITION);
export const Q_APICATALOG_APICATALOGMANIFEST = qualified(PG_SCHEMA_LAB, T_APICATALOG_APICATALOGMANIFEST);
export const Q_BITACORA_BITACORAREVISADO = qualified(PG_SCHEMA_LAB, T_BITACORA_BITACORAREVISADO);
export const Q_ORCHESTRATOR_APIKEYSLOT = qualified(PG_SCHEMA_LAB, T_ORCHESTRATOR_APIKEYSLOT);
export const Q_ORCHESTRATOR_ORCHESTRATORLEASE = qualified(PG_SCHEMA_LAB, T_ORCHESTRATOR_ORCHESTRATORLEASE);
export const Q_ORCHESTRATOR_CAPABILITYTIMING = qualified(PG_SCHEMA_LAB, T_ORCHESTRATOR_CAPABILITYTIMING);
export const Q_ORCHESTRATOR_ORCHESTRATORROTATIONLOG = qualified(PG_SCHEMA_LAB, T_ORCHESTRATOR_ORCHESTRATORROTATIONLOG);
export const Q_AUTH_AUTHUSER = qualified(PG_SCHEMA_LAB, T_AUTH_AUTHUSER);

export const Q_SEQ_STORE_STOREPROJECT = qualifiedSeq(PG_SCHEMA_LAB, SEQ_STORE_STOREPROJECT);
export const Q_SEQ_STORE_STORESECTION = qualifiedSeq(PG_SCHEMA_LAB, SEQ_STORE_STORESECTION);
export const Q_SEQ_ENTITY_ENTITYDEFINITION = qualifiedSeq(PG_SCHEMA_LAB, SEQ_ENTITY_ENTITYDEFINITION);

// --- ClientesIS entity store (BD_CLIENTESIS) ---
export const T_CLIENTESIS_ENTITYROW = "ENTITY_ENTITYROW";
export const Q_CLIENTESIS_ENTITYROW = qualified(PG_SCHEMA_CLIENTESIS, T_CLIENTESIS_ENTITYROW);

// --- RAG (BD_RAG) ---
export const T_INDEX_INDEXRUN = "INDEX_INDEXRUN";
export const T_VECTOR_VECCONTAPYME = "VECTOR_VECCONTAPYME";
export const T_VECTOR_VECFITDOCS = "VECTOR_VECFITDOCS";

export const Q_INDEX_INDEXRUN = qualified(PG_SCHEMA_RAG, T_INDEX_INDEXRUN);
export const Q_VECTOR_VECCONTAPYME = qualified(PG_SCHEMA_RAG, T_VECTOR_VECCONTAPYME);
export const Q_VECTOR_VECFITDOCS = qualified(PG_SCHEMA_RAG, T_VECTOR_VECFITDOCS);

/** Columnas entity row (SQL quoted, sin _). */
export const COL_ER = {
	PROJECT: pgQ("PROJECT"),
	PAGE: pgQ("PAGE"),
	ENTITY: pgQ("ENTITY"),
	IENTITYID: pgQ("IENTITYID"),
	BODY: pgQ("BODY"),
	PARENTPROJECT: pgQ("PARENTPROJECT"),
	PARENTPAGE: pgQ("PARENTPAGE"),
	PARENTENTITY: pgQ("PARENTENTITY"),
	IPARENTENTITYID: pgQ("IPARENTENTITYID"),
	SORTKEY: pgQ("SORTKEY"),
	TAGS: pgQ("TAGS"),
	FHCRE: pgQ("FHCRE"),
	FHULTACT: pgQ("FHULTACT"),
} as const;

/** Alias en SELECT para filas TS (minúsculas). */
export const COL_ER_ALIASES = {
	PROJECT: "project",
	PAGE: "page",
	ENTITY: "entity",
	IENTITYID: "ientityid",
	BODY: "body",
	PARENTPROJECT: "parentproject",
	PARENTPAGE: "parentpage",
	PARENTENTITY: "parententity",
	IPARENTENTITYID: "iparententityid",
	SORTKEY: "sortkey",
	TAGS: "tags",
	FHCRE: "fhcre",
	FHULTACT: "fhultact",
} as const;

export function selectEntityRowCols(prefix = ""): string {
	const p = prefix ? `${prefix}.` : "";
	const a = COL_ER_ALIASES;
	return [
		`${p}${COL_ER.PROJECT} AS ${a.PROJECT}`,
		`${p}${COL_ER.PAGE} AS ${a.PAGE}`,
		`${p}${COL_ER.ENTITY} AS ${a.ENTITY}`,
		`${p}${COL_ER.IENTITYID} AS ${a.IENTITYID}`,
		`${p}${COL_ER.BODY} AS ${a.BODY}`,
		`${p}${COL_ER.PARENTPROJECT} AS ${a.PARENTPROJECT}`,
		`${p}${COL_ER.PARENTPAGE} AS ${a.PARENTPAGE}`,
		`${p}${COL_ER.PARENTENTITY} AS ${a.PARENTENTITY}`,
		`${p}${COL_ER.IPARENTENTITYID} AS ${a.IPARENTENTITYID}`,
		`${p}${COL_ER.SORTKEY} AS ${a.SORTKEY}`,
		`${p}${COL_ER.TAGS} AS ${a.TAGS}`,
		`${p}${COL_ER.FHCRE} AS ${a.FHCRE}`,
		`${p}${COL_ER.FHULTACT} AS ${a.FHULTACT}`,
	].join(", ");
}

/** Columnas bitacora revisado */
export const COL_REV = {
	KEY: pgQ("REVISADOKEY"),
	BCHECKED: pgQ("BCHECKED"),
	FHULTACT: pgQ("FHULTACT"),
} as const;

export const COL_AUTH = {
	USERNAME: pgQ("USERNAME"),
	PASSWORDHASH: pgQ("PASSWORDHASH"),
	DISPLAYNAME: pgQ("DISPLAYNAME"),
	ACTIVE: pgQ("ACTIVE"),
	FHCRE: pgQ("FHCRE"),
	FHULTACT: pgQ("FHULTACT"),
} as const;

/** @deprecated usar IENTITYID */
export const COL_ER_PK = COL_ER.IENTITYID;

// --- Alias legacy (PATY_/LAB_/CIS_/RAG_ → dominio entidad) ---
export const T_PATY_CONVERSACION = T_CONVERSACION_CONVERSACION;
export const T_PATY_CONVERSACIONTURNO = T_CONVERSACION_CONVERSACIONTURNO;
export const T_PATY_MENSAJECALIFICADO = T_CONVERSACION_MENSAJECALIFICADO;
export const T_PATY_CONVERSACIONTURNOLOCK = T_CONVERSACION_CONVERSACIONTURNOLOCK;
export const T_PATY_CONVERSACIONTURNOTIMING = T_CONVERSACION_CONVERSACIONTURNOTIMING;
export const T_PATY_INSTRUCCION = T_INSTRUCCION_INSTRUCCION;
export const T_PATY_TDCONSULTA = T_TDCONSULTA_TDCONSULTA;
export const T_PATY_TDCONSULTAINSTRUCCION = T_TDCONSULTA_TDCONSULTAINSTRUCCION;
export const T_PATY_TDCONSULTACORPUS = T_TDCONSULTA_TDCONSULTACORPUS;

export const Q_PATY_CONVERSACION = Q_CONVERSACION_CONVERSACION;
export const Q_PATY_CONVERSACIONTURNO = Q_CONVERSACION_CONVERSACIONTURNO;
export const Q_PATY_MENSAJECALIFICADO = Q_CONVERSACION_MENSAJECALIFICADO;
export const Q_PATY_CONVERSACIONTURNOLOCK = Q_CONVERSACION_CONVERSACIONTURNOLOCK;
export const Q_PATY_CONVERSACIONTURNOTIMING = Q_CONVERSACION_CONVERSACIONTURNOTIMING;
export const Q_PATY_INSTRUCCION = Q_INSTRUCCION_INSTRUCCION;
export const Q_PATY_TDCONSULTA = Q_TDCONSULTA_TDCONSULTA;
export const Q_PATY_TDCONSULTAINSTRUCCION = Q_TDCONSULTA_TDCONSULTAINSTRUCCION;
export const Q_PATY_TDCONSULTACORPUS = Q_TDCONSULTA_TDCONSULTACORPUS;

export const T_LAB_ENTITYROW = T_ENTITY_ENTITYROW;
export const T_LAB_STOREPROJECT = T_STORE_STOREPROJECT;
export const T_LAB_STORESECTION = T_STORE_STORESECTION;
export const T_LAB_ENTITYDEFINITION = T_ENTITY_ENTITYDEFINITION;
export const T_LAB_APICATALOGMANIFEST = T_APICATALOG_APICATALOGMANIFEST;
export const T_LAB_BITACORAREVISADO = T_BITACORA_BITACORAREVISADO;
export const T_LAB_APIKEYSLOT = T_ORCHESTRATOR_APIKEYSLOT;
export const T_LAB_ORCHESTRATORLEASE = T_ORCHESTRATOR_ORCHESTRATORLEASE;
export const T_LAB_CAPABILITYTIMING = T_ORCHESTRATOR_CAPABILITYTIMING;
export const T_LAB_ORCHESTRATORROTATIONLOG = T_ORCHESTRATOR_ORCHESTRATORROTATIONLOG;
export const T_LAB_AUTHUSER = T_AUTH_AUTHUSER;

export const SEQ_LAB_STOREPROJECT = SEQ_STORE_STOREPROJECT;
export const SEQ_LAB_STORESECTION = SEQ_STORE_STORESECTION;
export const SEQ_LAB_ENTITYDEFINITION = SEQ_ENTITY_ENTITYDEFINITION;

export const Q_LAB_ENTITY_ROW = Q_ENTITY_ENTITYROW;
export const Q_LAB_STORE_PROJECT = Q_STORE_STOREPROJECT;
export const Q_LAB_STORE_SECTION = Q_STORE_STORESECTION;
export const Q_LAB_ENTITY_DEFINITION = Q_ENTITY_ENTITYDEFINITION;
export const Q_LAB_API_CATALOG_MANIFEST = Q_APICATALOG_APICATALOGMANIFEST;
export const Q_LAB_BITACORA_REVISADO = Q_BITACORA_BITACORAREVISADO;
export const Q_LAB_API_KEY_SLOT = Q_ORCHESTRATOR_APIKEYSLOT;
export const Q_LAB_ORCHESTRATOR_LEASE = Q_ORCHESTRATOR_ORCHESTRATORLEASE;
export const Q_LAB_CAPABILITY_TIMING = Q_ORCHESTRATOR_CAPABILITYTIMING;
export const Q_LAB_ORCHESTRATOR_ROTATION_LOG = Q_ORCHESTRATOR_ORCHESTRATORROTATIONLOG;
export const Q_LAB_AUTH_USER = Q_AUTH_AUTHUSER;

export const Q_SEQ_LAB_STORE_PROJECT = Q_SEQ_STORE_STOREPROJECT;
export const Q_SEQ_LAB_STORE_SECTION = Q_SEQ_STORE_STORESECTION;
export const Q_SEQ_LAB_ENTITY_DEFINITION = Q_SEQ_ENTITY_ENTITYDEFINITION;

export const T_CIS_ENTITYROW = T_CLIENTESIS_ENTITYROW;
export const Q_CIS_ENTITY_ROW = Q_CLIENTESIS_ENTITYROW;

export const T_RAG_INDEXRUN = T_INDEX_INDEXRUN;
export const T_RAG_VECCONTAPYME = T_VECTOR_VECCONTAPYME;
export const T_RAG_VECFITDOCS = T_VECTOR_VECFITDOCS;
export const Q_RAG_INDEX_RUN = Q_INDEX_INDEXRUN;
export const Q_RAG_VEC_CONTAPYME = Q_VECTOR_VECCONTAPYME;
export const Q_RAG_VEC_FITDOCS = Q_VECTOR_VECFITDOCS;

export const Q_PATY_CONVERSACION_TURNO = Q_CONVERSACION_CONVERSACIONTURNO;
export const Q_PATY_MENSAJE_CALIFICADO = Q_CONVERSACION_MENSAJECALIFICADO;
export const Q_PATY_CONVERSACION_TURNO_LOCK = Q_CONVERSACION_CONVERSACIONTURNOLOCK;
export const Q_PATY_CONVERSACION_TURNO_TIMING = Q_CONVERSACION_CONVERSACIONTURNOTIMING;
export const Q_PATY_TDCONSULTA_INSTRUCCION = Q_TDCONSULTA_TDCONSULTAINSTRUCCION;
export const Q_PATY_TDCONSULTA_CORPUS = Q_TDCONSULTA_TDCONSULTACORPUS;
export const T_PATY_CONVERSACION_TURNO = T_CONVERSACION_CONVERSACIONTURNO;
export const T_PATY_CONVERSACION_TURNO_LOCK = T_CONVERSACION_CONVERSACIONTURNOLOCK;
export const T_PATY_CONVERSACION_TURNO_TIMING = T_CONVERSACION_CONVERSACIONTURNOTIMING;
export const T_LAB_API_KEY_SLOT = T_ORCHESTRATOR_APIKEYSLOT;
export const T_LAB_ORCHESTRATOR_LEASE = T_ORCHESTRATOR_ORCHESTRATORLEASE;
export const T_LAB_CAPABILITY_TIMING = T_ORCHESTRATOR_CAPABILITYTIMING;
export const T_LAB_ORCHESTRATOR_ROTATION_LOG = T_ORCHESTRATOR_ORCHESTRATORROTATIONLOG;
export const T_LAB_ENTITY_ROW = T_ENTITY_ENTITYROW;
export const T_CIS_ENTITY_ROW = T_CLIENTESIS_ENTITYROW;
export const T_RAG_VEC_CONTAPYME = T_VECTOR_VECCONTAPYME;
export const T_RAG_VEC_FITDOCS = T_VECTOR_VECFITDOCS;
export const T_RAG_INDEX_RUN = T_INDEX_INDEXRUN;
