/**
 * Renombres → nomenclatura simplificada (sin duplicar dominio: CONVERSACION, no CONVERSACION_CONVERSACION).
 * Orden importa: de nombres más específicos / legacy a canónicos.
 */
import type { TableRename } from "./entity-domain-rename-map.js";

export const SIMPLIFY_TABLE_RENAMES: TableRename[] = [
	// BD_LANGLAB — conversación
	{ schema: "BD_LANGLAB", oldTable: "paty_conversacion", newTable: "CONVERSACION" },
	{ schema: "BD_LANGLAB", oldTable: "PATY_CONVERSACION", newTable: "CONVERSACION" },
	{ schema: "BD_LANGLAB", oldTable: "CONVERSACION_CONVERSACION", newTable: "CONVERSACION" },
	{ schema: "BD_LANGLAB", oldTable: "paty_conversacion_turno", newTable: "CONVERSACION_TURNO" },
	{ schema: "BD_LANGLAB", oldTable: "PATY_CONVERSACIONTURNO", newTable: "CONVERSACION_TURNO" },
	{ schema: "BD_LANGLAB", oldTable: "CONVERSACION_CONVERSACIONTURNO", newTable: "CONVERSACION_TURNO" },
	{ schema: "BD_LANGLAB", oldTable: "paty_mensaje_calificado", newTable: "CONVERSACION_MENSAJE" },
	{ schema: "BD_LANGLAB", oldTable: "PATY_MENSAJECALIFICADO", newTable: "CONVERSACION_MENSAJE" },
	{ schema: "BD_LANGLAB", oldTable: "CONVERSACION_MENSAJECALIFICADO", newTable: "CONVERSACION_MENSAJE" },
	{ schema: "BD_LANGLAB", oldTable: "paty_conversacion_turno_lock", newTable: "CONVERSACION_TURNOLOCK" },
	{ schema: "BD_LANGLAB", oldTable: "PATY_CONVERSACIONTURNOLOCK", newTable: "CONVERSACION_TURNOLOCK" },
	{ schema: "BD_LANGLAB", oldTable: "CONVERSACION_CONVERSACIONTURNOLOCK", newTable: "CONVERSACION_TURNOLOCK" },
	{ schema: "BD_LANGLAB", oldTable: "paty_conversacion_turno_timing", newTable: "CONVERSACION_TURNOTIMING" },
	{ schema: "BD_LANGLAB", oldTable: "PATY_CONVERSACIONTURNOTIMING", newTable: "CONVERSACION_TURNOTIMING" },
	{ schema: "BD_LANGLAB", oldTable: "CONVERSACION_CONVERSACIONTURNOTIMING", newTable: "CONVERSACION_TURNOTIMING" },
	// BD_LANGLAB — prompts
	{ schema: "BD_LANGLAB", oldTable: "paty_instruccion", newTable: "INSTRUCCION" },
	{ schema: "BD_LANGLAB", oldTable: "PATY_INSTRUCCION", newTable: "INSTRUCCION" },
	{ schema: "BD_LANGLAB", oldTable: "INSTRUCCION_INSTRUCCION", newTable: "INSTRUCCION" },
	{ schema: "BD_LANGLAB", oldTable: "paty_tdconsulta", newTable: "TDCONSULTA" },
	{ schema: "BD_LANGLAB", oldTable: "PATY_TDCONSULTA", newTable: "TDCONSULTA" },
	{ schema: "BD_LANGLAB", oldTable: "TDCONSULTA_TDCONSULTA", newTable: "TDCONSULTA" },
	{ schema: "BD_LANGLAB", oldTable: "paty_tdconsulta_instruccion", newTable: "TDCONSULTA_INSTRUCCION" },
	{ schema: "BD_LANGLAB", oldTable: "PATY_TDCONSULTAINSTRUCCION", newTable: "TDCONSULTA_INSTRUCCION" },
	{ schema: "BD_LANGLAB", oldTable: "TDCONSULTA_TDCONSULTAINSTRUCCION", newTable: "TDCONSULTA_INSTRUCCION" },
	{ schema: "BD_LANGLAB", oldTable: "paty_tdconsulta_corpus", newTable: "TDCONSULTA_CORPUS" },
	{ schema: "BD_LANGLAB", oldTable: "PATY_TDCONSULTACORPUS", newTable: "TDCONSULTA_CORPUS" },
	{ schema: "BD_LANGLAB", oldTable: "TDCONSULTA_TDCONSULTACORPUS", newTable: "TDCONSULTA_CORPUS" },
	// BD_LAB
	{ schema: "BD_LAB", oldTable: "lab_entity_row", newTable: "ENTITY_ROW" },
	{ schema: "BD_LAB", oldTable: "LAB_ENTITYROW", newTable: "ENTITY_ROW" },
	{ schema: "BD_LAB", oldTable: "ENTITY_ENTITYROW", newTable: "ENTITY_ROW" },
	{ schema: "BD_LAB", oldTable: "lab_store_project", newTable: "STORE_PROJECT" },
	{ schema: "BD_LAB", oldTable: "LAB_STOREPROJECT", newTable: "STORE_PROJECT" },
	{ schema: "BD_LAB", oldTable: "STORE_STOREPROJECT", newTable: "STORE_PROJECT" },
	{ schema: "BD_LAB", oldTable: "lab_store_section", newTable: "STORE_SECTION" },
	{ schema: "BD_LAB", oldTable: "LAB_STORESECTION", newTable: "STORE_SECTION" },
	{ schema: "BD_LAB", oldTable: "STORE_STORESECTION", newTable: "STORE_SECTION" },
	{ schema: "BD_LAB", oldTable: "lab_entity_definition", newTable: "ENTITY_DEFINITION" },
	{ schema: "BD_LAB", oldTable: "LAB_ENTITYDEFINITION", newTable: "ENTITY_DEFINITION" },
	{ schema: "BD_LAB", oldTable: "ENTITY_ENTITYDEFINITION", newTable: "ENTITY_DEFINITION" },
	{ schema: "BD_LAB", oldTable: "lab_api_catalog_manifest", newTable: "APICATALOG_MANIFEST" },
	{ schema: "BD_LAB", oldTable: "LAB_APICATALOGMANIFEST", newTable: "APICATALOG_MANIFEST" },
	{ schema: "BD_LAB", oldTable: "APICATALOG_APICATALOGMANIFEST", newTable: "APICATALOG_MANIFEST" },
	{ schema: "BD_LAB", oldTable: "lab_bitacora_revisado", newTable: "BITACORA_REVISADO" },
	{ schema: "BD_LAB", oldTable: "LAB_BITACORAREVISADO", newTable: "BITACORA_REVISADO" },
	{ schema: "BD_LAB", oldTable: "BITACORA_BITACORAREVISADO", newTable: "BITACORA_REVISADO" },
	{ schema: "BD_LAB", oldTable: "lab_api_key_slot", newTable: "ORCHESTRATOR_SLOT" },
	{ schema: "BD_LAB", oldTable: "LAB_APIKEYSLOT", newTable: "ORCHESTRATOR_SLOT" },
	{ schema: "BD_LAB", oldTable: "ORCHESTRATOR_APIKEYSLOT", newTable: "ORCHESTRATOR_SLOT" },
	{ schema: "BD_LAB", oldTable: "lab_orchestrator_lease", newTable: "ORCHESTRATOR_LEASE" },
	{ schema: "BD_LAB", oldTable: "LAB_ORCHESTRATORLEASE", newTable: "ORCHESTRATOR_LEASE" },
	{ schema: "BD_LAB", oldTable: "ORCHESTRATOR_ORCHESTRATORLEASE", newTable: "ORCHESTRATOR_LEASE" },
	{ schema: "BD_LAB", oldTable: "lab_capability_timing", newTable: "ORCHESTRATOR_CAPABILITY" },
	{ schema: "BD_LAB", oldTable: "LAB_CAPABILITYTIMING", newTable: "ORCHESTRATOR_CAPABILITY" },
	{ schema: "BD_LAB", oldTable: "ORCHESTRATOR_CAPABILITYTIMING", newTable: "ORCHESTRATOR_CAPABILITY" },
	{ schema: "BD_LAB", oldTable: "lab_orchestrator_rotation_log", newTable: "ORCHESTRATOR_ROTATIONLOG" },
	{ schema: "BD_LAB", oldTable: "LAB_ORCHESTRATORROTATIONLOG", newTable: "ORCHESTRATOR_ROTATIONLOG" },
	{ schema: "BD_LAB", oldTable: "ORCHESTRATOR_ORCHESTRATORROTATIONLOG", newTable: "ORCHESTRATOR_ROTATIONLOG" },
	{ schema: "BD_LAB", oldTable: "lab_auth_user", newTable: "AUTH_USER" },
	{ schema: "BD_LAB", oldTable: "LAB_AUTHUSER", newTable: "AUTH_USER" },
	{ schema: "BD_LAB", oldTable: "AUTH_AUTHUSER", newTable: "AUTH_USER" },
	// BD_CLIENTESIS / BD_RAG
	{ schema: "BD_CLIENTESIS", oldTable: "cis_entity_row", newTable: "ENTITY_ROW" },
	{ schema: "BD_CLIENTESIS", oldTable: "CIS_ENTITYROW", newTable: "ENTITY_ROW" },
	{ schema: "BD_RAG", oldTable: "rag_index_run", newTable: "INDEX_RUN" },
	{ schema: "BD_RAG", oldTable: "RAG_INDEXRUN", newTable: "INDEX_RUN" },
	{ schema: "BD_RAG", oldTable: "INDEX_INDEXRUN", newTable: "INDEX_RUN" },
	{ schema: "BD_RAG", oldTable: "rag_vec_contapyme", newTable: "VECTOR_CONTAPYME" },
	{ schema: "BD_RAG", oldTable: "RAG_VECCONTAPYME", newTable: "VECTOR_CONTAPYME" },
	{ schema: "BD_RAG", oldTable: "VECTOR_VECCONTAPYME", newTable: "VECTOR_CONTAPYME" },
];
