CREATE SCHEMA IF NOT EXISTS "BD_CLIENTESIS";

CREATE TABLE IF NOT EXISTS "BD_CLIENTESIS"."ENTITY_ENTITYROW" (
	"PROJECT" TEXT NOT NULL,
	"PAGE" TEXT NOT NULL,
	"ENTITY" TEXT NOT NULL,
	"IENTITYID" TEXT NOT NULL,
	"BODY" JSONB NOT NULL DEFAULT '{}',
	"PARENTPROJECT" TEXT,
	"PARENTPAGE" TEXT,
	"PARENTENTITY" TEXT,
	"IPARENTENTITYID" TEXT,
	"SORTKEY" INT NOT NULL DEFAULT 0,
	"TAGS" TEXT[] NOT NULL DEFAULT '{}',
	"FHCRE" TIMESTAMPTZ NOT NULL DEFAULT now(),
	"FHULTACT" TIMESTAMPTZ NOT NULL DEFAULT now(),
	PRIMARY KEY ("PROJECT", "PAGE", "ENTITY", "IENTITYID")
);

CREATE INDEX IF NOT EXISTS "IX_ENTITY_ENTITYROW_SEGMENT" ON "BD_CLIENTESIS"."ENTITY_ENTITYROW" ("PROJECT", "PAGE", "ENTITY");
CREATE INDEX IF NOT EXISTS "IX_ENTITY_ENTITYROW_PARENT" ON "BD_CLIENTESIS"."ENTITY_ENTITYROW" ("PARENTPROJECT", "PARENTPAGE", "PARENTENTITY", "IPARENTENTITYID") WHERE "IPARENTENTITYID" IS NOT NULL;
CREATE INDEX IF NOT EXISTS "IX_ENTITY_ENTITYROW_TAGS" ON "BD_CLIENTESIS"."ENTITY_ENTITYROW" USING gin ("TAGS");
