export {
	Q_LAB_API_KEY_SLOT,
	Q_LAB_ORCHESTRATOR_LEASE,
	Q_LAB_CAPABILITY_TIMING,
	Q_LAB_ORCHESTRATOR_ROTATION_LOG,
	Q_PATY_CONVERSACION_TURNO_LOCK,
	Q_PATY_CONVERSACION_TURNO_TIMING,
} from "../db/pg-identifiers.js";
