/** Funciones SQL en BD_PATY (nomenclatura post-migración entidad). */
export const FN_CONVERSACION_NEXT_TURN_INDEX = '"BD_PATY"."CONVERSACION_NEXTTURNINDEX"';
export const FN_ORCHESTRATOR_EXPIRE_STALE_LEASES = '"BD_PATY"."ORCHESTRATOR_EXPIRESTALORCHESTRATORLEASES"';
