-- LangLab operacional · esquema BD_LANGLAB (nomenclatura INSOFT, columnas sin _)
-- Primero: renombrar tablas legacy → nombres simplificados (CONVERSACION, no CONVERSACION_CONVERSACION).

CREATE SCHEMA IF NOT EXISTS "BD_LANGLAB";
CREATE SCHEMA IF NOT EXISTS "BD_LANGLAB";
CREATE SCHEMA IF NOT EXISTS "BD_CLIENTESIS";

CREATE OR REPLACE FUNCTION "BD_LANGLAB"."_simplify_rename_table"(
	p_schema TEXT, p_old TEXT, p_new TEXT
) RETURNS VOID LANGUAGE plpgsql AS $$
BEGIN
	IF p_old = p_new THEN RETURN; END IF;
	IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = p_schema AND table_name = p_old) THEN RETURN; END IF;
	IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = p_schema AND table_name = p_new) THEN
		EXECUTE format('DROP TABLE %I.%I', p_schema, p_old);
		RETURN;
	END IF;
	EXECUTE format('ALTER TABLE %I.%I RENAME TO %I', p_schema, p_old, p_new);
END;
$$;

CREATE OR REPLACE FUNCTION "BD_LANGLAB"."_simplify_uppercase_columns"(
	p_schema TEXT, p_table TEXT
) RETURNS VOID LANGUAGE plpgsql AS $$
DECLARE r RECORD; new_name TEXT;
BEGIN
	IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = p_schema AND table_name = p_table) THEN RETURN; END IF;
	FOR r IN SELECT column_name FROM information_schema.columns WHERE table_schema = p_schema AND table_name = p_table LOOP
		new_name := upper(replace(r.column_name, '_', ''));
		IF r.column_name IS DISTINCT FROM new_name THEN
			EXECUTE format('ALTER TABLE %I.%I RENAME COLUMN %I TO %I', p_schema, p_table, r.column_name, new_name);
		END IF;
	END LOOP;
END;
$$;

DO $$
DECLARE r RECORD;
BEGIN
	CREATE SCHEMA IF NOT EXISTS "BD_LANGLAB";
	-- Esquema legacy bd_lab: eliminar siempre (datos viven en BD_LAB tras migración).
	IF EXISTS (SELECT 1 FROM pg_namespace WHERE nspname = 'bd_lab') THEN
		DROP SCHEMA bd_lab CASCADE;
	END IF;
	FOR r IN SELECT tablename FROM pg_tables WHERE schemaname = 'paty' LOOP
		IF EXISTS (SELECT 1 FROM pg_tables WHERE schemaname = 'BD_LANGLAB' AND tablename = r.tablename) THEN
			EXECUTE format('DROP TABLE paty.%I', r.tablename);
		ELSE
			EXECUTE format('ALTER TABLE paty.%I SET SCHEMA "BD_LANGLAB"', r.tablename);
		END IF;
	END LOOP;

	PERFORM "BD_LANGLAB"."_simplify_rename_table"('BD_LANGLAB', 'paty_conversacion', 'CONVERSACION');
	PERFORM "BD_LANGLAB"."_simplify_rename_table"('BD_LANGLAB', 'PATY_CONVERSACION', 'CONVERSACION');
	PERFORM "BD_LANGLAB"."_simplify_rename_table"('BD_LANGLAB', 'CONVERSACION_CONVERSACION', 'CONVERSACION');
	PERFORM "BD_LANGLAB"."_simplify_rename_table"('BD_LANGLAB', 'paty_conversacion_turno', 'CONVERSACION_TURNO');
	PERFORM "BD_LANGLAB"."_simplify_rename_table"('BD_LANGLAB', 'PATY_CONVERSACIONTURNO', 'CONVERSACION_TURNO');
	PERFORM "BD_LANGLAB"."_simplify_rename_table"('BD_LANGLAB', 'CONVERSACION_CONVERSACIONTURNO', 'CONVERSACION_TURNO');
	PERFORM "BD_LANGLAB"."_simplify_rename_table"('BD_LANGLAB', 'paty_mensaje_calificado', 'CONVERSACION_MENSAJE');
	PERFORM "BD_LANGLAB"."_simplify_rename_table"('BD_LANGLAB', 'PATY_MENSAJECALIFICADO', 'CONVERSACION_MENSAJE');
	PERFORM "BD_LANGLAB"."_simplify_rename_table"('BD_LANGLAB', 'CONVERSACION_MENSAJECALIFICADO', 'CONVERSACION_MENSAJE');
	PERFORM "BD_LANGLAB"."_simplify_rename_table"('BD_LANGLAB', 'paty_conversacion_turno_lock', 'CONVERSACION_TURNOLOCK');
	PERFORM "BD_LANGLAB"."_simplify_rename_table"('BD_LANGLAB', 'PATY_CONVERSACIONTURNOLOCK', 'CONVERSACION_TURNOLOCK');
	PERFORM "BD_LANGLAB"."_simplify_rename_table"('BD_LANGLAB', 'CONVERSACION_CONVERSACIONTURNOLOCK', 'CONVERSACION_TURNOLOCK');
	PERFORM "BD_LANGLAB"."_simplify_rename_table"('BD_LANGLAB', 'paty_conversacion_turno_timing', 'CONVERSACION_TURNOTIMING');
	PERFORM "BD_LANGLAB"."_simplify_rename_table"('BD_LANGLAB', 'PATY_CONVERSACIONTURNOTIMING', 'CONVERSACION_TURNOTIMING');
	PERFORM "BD_LANGLAB"."_simplify_rename_table"('BD_LANGLAB', 'CONVERSACION_CONVERSACIONTURNOTIMING', 'CONVERSACION_TURNOTIMING');
	PERFORM "BD_LANGLAB"."_simplify_rename_table"('BD_LANGLAB', 'paty_instruccion', 'INSTRUCCION');
	PERFORM "BD_LANGLAB"."_simplify_rename_table"('BD_LANGLAB', 'PATY_INSTRUCCION', 'INSTRUCCION');
	PERFORM "BD_LANGLAB"."_simplify_rename_table"('BD_LANGLAB', 'INSTRUCCION_INSTRUCCION', 'INSTRUCCION');
	PERFORM "BD_LANGLAB"."_simplify_rename_table"('BD_LANGLAB', 'paty_tdconsulta', 'TDCONSULTA');
	PERFORM "BD_LANGLAB"."_simplify_rename_table"('BD_LANGLAB', 'PATY_TDCONSULTA', 'TDCONSULTA');
	PERFORM "BD_LANGLAB"."_simplify_rename_table"('BD_LANGLAB', 'TDCONSULTA_TDCONSULTA', 'TDCONSULTA');
	PERFORM "BD_LANGLAB"."_simplify_rename_table"('BD_LANGLAB', 'paty_tdconsulta_instruccion', 'TDCONSULTA_INSTRUCCION');
	PERFORM "BD_LANGLAB"."_simplify_rename_table"('BD_LANGLAB', 'PATY_TDCONSULTAINSTRUCCION', 'TDCONSULTA_INSTRUCCION');
	PERFORM "BD_LANGLAB"."_simplify_rename_table"('BD_LANGLAB', 'TDCONSULTA_TDCONSULTAINSTRUCCION', 'TDCONSULTA_INSTRUCCION');
	PERFORM "BD_LANGLAB"."_simplify_rename_table"('BD_LANGLAB', 'paty_tdconsulta_corpus', 'TDCONSULTA_CORPUS');
	PERFORM "BD_LANGLAB"."_simplify_rename_table"('BD_LANGLAB', 'PATY_TDCONSULTACORPUS', 'TDCONSULTA_CORPUS');
	PERFORM "BD_LANGLAB"."_simplify_rename_table"('BD_LANGLAB', 'TDCONSULTA_TDCONSULTACORPUS', 'TDCONSULTA_CORPUS');
	PERFORM "BD_LANGLAB"."_simplify_rename_table"('BD_LANGLAB', 'lab_entity_row', 'ENTITY_ROW');
	PERFORM "BD_LANGLAB"."_simplify_rename_table"('BD_LANGLAB', 'LAB_ENTITYROW', 'ENTITY_ROW');
	PERFORM "BD_LANGLAB"."_simplify_rename_table"('BD_LANGLAB', 'ENTITY_ENTITYROW', 'ENTITY_ROW');
	PERFORM "BD_LANGLAB"."_simplify_rename_table"('BD_LANGLAB', 'lab_orchestrator_lease', 'ORCHESTRATOR_LEASE');
	PERFORM "BD_LANGLAB"."_simplify_rename_table"('BD_LANGLAB', 'LAB_ORCHESTRATORLEASE', 'ORCHESTRATOR_LEASE');
	PERFORM "BD_LANGLAB"."_simplify_rename_table"('BD_LANGLAB', 'ORCHESTRATOR_ORCHESTRATORLEASE', 'ORCHESTRATOR_LEASE');
	PERFORM "BD_LANGLAB"."_simplify_rename_table"('BD_LANGLAB', 'lab_api_key_slot', 'ORCHESTRATOR_SLOT');
	PERFORM "BD_LANGLAB"."_simplify_rename_table"('BD_LANGLAB', 'LAB_APIKEYSLOT', 'ORCHESTRATOR_SLOT');
	PERFORM "BD_LANGLAB"."_simplify_rename_table"('BD_LANGLAB', 'ORCHESTRATOR_APIKEYSLOT', 'ORCHESTRATOR_SLOT');
	PERFORM "BD_LANGLAB"."_simplify_rename_table"('BD_LANGLAB', 'lab_capability_timing', 'ORCHESTRATOR_CAPABILITY');
	PERFORM "BD_LANGLAB"."_simplify_rename_table"('BD_LANGLAB', 'LAB_CAPABILITYTIMING', 'ORCHESTRATOR_CAPABILITY');
	PERFORM "BD_LANGLAB"."_simplify_rename_table"('BD_LANGLAB', 'ORCHESTRATOR_CAPABILITYTIMING', 'ORCHESTRATOR_CAPABILITY');
END;
$$;

DO $$
DECLARE t TEXT;
BEGIN
	FOREACH t IN ARRAY ARRAY[
		'CONVERSACION', 'CONVERSACION_TURNO', 'CONVERSACION_MENSAJE',
		'CONVERSACION_TURNOLOCK', 'CONVERSACION_TURNOTIMING',
		'INSTRUCCION', 'TDCONSULTA', 'TDCONSULTA_INSTRUCCION', 'TDCONSULTA_CORPUS'
	] LOOP
		PERFORM "BD_LANGLAB"."_simplify_uppercase_columns"('BD_LANGLAB', t);
	END LOOP;
	FOREACH t IN ARRAY ARRAY['ORCHESTRATOR_LEASE', 'ORCHESTRATOR_SLOT', 'ORCHESTRATOR_CAPABILITY'] LOOP
		PERFORM "BD_LANGLAB"."_simplify_uppercase_columns"('BD_LANGLAB', t);
	END LOOP;
END;
$$;

DROP FUNCTION IF EXISTS "BD_LANGLAB"."_simplify_rename_table"(TEXT, TEXT, TEXT);
DROP FUNCTION IF EXISTS "BD_LANGLAB"."_simplify_uppercase_columns"(TEXT, TEXT);

CREATE TABLE IF NOT EXISTS "BD_LANGLAB"."TDCONSULTA" (
	"ITDCONSULTA" TEXT PRIMARY KEY,
	"NCONSULTA" TEXT NOT NULL DEFAULT '',
	"DESCRIPCION" TEXT NOT NULL DEFAULT '',
	"BACTIVO" BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS "BD_LANGLAB"."INSTRUCCION" (
	"IINSTRUCCION" TEXT PRIMARY KEY,
	"NINSTRUCCION" TEXT NOT NULL,
	"MODELO" TEXT NOT NULL DEFAULT '',
	"INSTRUCCION" TEXT NOT NULL,
	"DESCRIPCION" TEXT NOT NULL DEFAULT '',
	"VERSION" TEXT NOT NULL DEFAULT 'ultra',
	"BACTIVO" BOOLEAN NOT NULL DEFAULT TRUE,
	"FHINI" TIMESTAMPTZ,
	"FHFIN" TIMESTAMPTZ,
	"FHULTACT" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "BD_LANGLAB"."TDCONSULTA_INSTRUCCION" (
	"ITDCONSULTA" TEXT NOT NULL,
	"IINSTRUCCION" TEXT NOT NULL,
	"IORDEN" INT NOT NULL DEFAULT 1,
	PRIMARY KEY ("ITDCONSULTA", "IINSTRUCCION")
);

CREATE TABLE IF NOT EXISTS "BD_LANGLAB"."TDCONSULTA_CORPUS" (
	"ITDCONSULTA" TEXT NOT NULL,
	"CORPUS" TEXT NOT NULL,
	"IORDEN" INT NOT NULL DEFAULT 1,
	PRIMARY KEY ("ITDCONSULTA", "CORPUS")
);

CREATE TABLE IF NOT EXISTS "BD_LANGLAB"."CONVERSACION" (
	"ICONVERSACION" BIGSERIAL PRIMARY KEY,
	"ITERCERO" TEXT NOT NULL DEFAULT 'lab',
	"ICONTACTO" TEXT NOT NULL DEFAULT 'lab',
	"NOMBREUSUARIO" TEXT NOT NULL DEFAULT 'Usuario',
	"TITULO" TEXT NOT NULL DEFAULT '',
	"HILO" TEXT NOT NULL DEFAULT '',
	"MODELOIA" TEXT NOT NULL DEFAULT '',
	"VERSIONAYUDA" TEXT NOT NULL DEFAULT 'lab-langgraph',
	"ITDESTADO" SMALLINT NOT NULL DEFAULT 0,
	"BAUTORIZAVISUALIZACION" BOOLEAN NOT NULL DEFAULT FALSE,
	"IMODULO" TEXT NOT NULL DEFAULT '',
	"PROMPT" TEXT NOT NULL DEFAULT '',
	"RESPUESTA" TEXT NOT NULL DEFAULT '',
	"QTOKENS" BIGINT NOT NULL DEFAULT 0,
	"QMENSAJES" INT NOT NULL DEFAULT 0,
	"FHCRE" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	"FHULTACT" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "BD_LANGLAB"."CONVERSACION_TURNO" (
	"ITURNO" BIGSERIAL PRIMARY KEY,
	"ICONVERSACION" BIGINT NOT NULL,
	"TS" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	"PROMPTTEXT" TEXT NOT NULL,
	"RESPONSETEXT" TEXT NOT NULL,
	"PROMPTTIPO" TEXT,
	"CORPUS" TEXT[],
	"BJAILBREAK" BOOLEAN NOT NULL DEFAULT FALSE,
	"LATENCYMS" INT,
	"META" JSONB NOT NULL DEFAULT '{}'
);

CREATE INDEX IF NOT EXISTS "IX_CONVERSACION_TURNO_ICONVERSACION"
	ON "BD_LANGLAB"."CONVERSACION_TURNO" ("ICONVERSACION", "TS");

CREATE TABLE IF NOT EXISTS "BD_LANGLAB"."CONVERSACION_MENSAJE" (
	"IMENSAJE" BIGSERIAL PRIMARY KEY,
	"ICONVERSACION" BIGINT NOT NULL,
	"ITURNO" BIGINT,
	"IORDEN" INT NOT NULL DEFAULT 0,
	"DIRECCION" TEXT NOT NULL DEFAULT 'OUTPUT',
	"ROL" TEXT NOT NULL DEFAULT 'usuario',
	"CONTENIDO" TEXT NOT NULL DEFAULT '',
	"IREFERENCIA" BIGINT,
	"FHCRE" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS "IX_CONVERSACION_MENSAJE_ICONVERSACION"
	ON "BD_LANGLAB"."CONVERSACION_MENSAJE" ("ICONVERSACION");

CREATE TABLE IF NOT EXISTS "BD_LANGLAB"."CONVERSACION_MENSAJE_METRICAS" (
	"IMETRICA" BIGSERIAL PRIMARY KEY,
	"IMENSAJE" BIGINT NOT NULL,
	"ITURNO" BIGINT,
	"QTOKENSENTRADA" INT,
	"QTOKENSSALIDA" INT,
	"LATENCYMS" INT,
	"PROVIDER" TEXT,
	"MODELO" TEXT,
	"CALIFICACION" INT,
	"COMENTARIO" TEXT,
	"BUTIL" BOOLEAN,
	"META" JSONB NOT NULL DEFAULT '{}',
	"FHCRE" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	UNIQUE ("IMENSAJE")
);
