-- Orquestador · esquema BD_LAB (nomenclatura canónica)

CREATE SCHEMA IF NOT EXISTS "BD_LANGLAB";

CREATE TABLE IF NOT EXISTS "BD_LANGLAB"."ORCHESTRATOR_SLOT" (
	"PROVIDER" TEXT NOT NULL,
	"CAPABILITY" TEXT NOT NULL,
	"KEYLABEL" TEXT NOT NULL,
	"SORTORDER" INT NOT NULL DEFAULT 0,
	"BENABLED" BOOLEAN NOT NULL DEFAULT TRUE,
	"COOLDOWNUNTIL" TIMESTAMPTZ,
	"LASTUSEDAT" TIMESTAMPTZ,
	"LASTHTTPSTATUS" INT,
	"LASTERROR" TEXT,
	"WAITMSHINT" INT,
	"CONSECUTIVEFAILURES" INT NOT NULL DEFAULT 0,
	"META" JSONB NOT NULL DEFAULT '{}',
	"FHULTACT" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	PRIMARY KEY ("PROVIDER", "CAPABILITY", "KEYLABEL")
);

CREATE INDEX IF NOT EXISTS "IX_ORCHESTRATOR_SLOT_PICK"
	ON "BD_LANGLAB"."ORCHESTRATOR_SLOT" ("CAPABILITY", "PROVIDER", "BENABLED", "COOLDOWNUNTIL", "SORTORDER");

CREATE TABLE IF NOT EXISTS "BD_LANGLAB"."ORCHESTRATOR_LEASE" (
	"ILEASE" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
	"PROVIDER" TEXT NOT NULL,
	"CAPABILITY" TEXT NOT NULL,
	"KEYLABEL" TEXT NOT NULL,
	"ACQUIREDAT" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	"EXPIRESAT" TIMESTAMPTZ NOT NULL DEFAULT (NOW() + INTERVAL '45 minutes'),
	"RELEASEDAT" TIMESTAMPTZ,
	"BOK" BOOLEAN,
	"LASTERROR" TEXT,
	"WAITMSAPPLIED" INT,
	"META" JSONB NOT NULL DEFAULT '{}'
);

CREATE INDEX IF NOT EXISTS "IX_ORCHESTRATOR_LEASE_ACTIVE"
	ON "BD_LANGLAB"."ORCHESTRATOR_LEASE" ("CAPABILITY", "PROVIDER", "RELEASEDAT")
	WHERE "RELEASEDAT" IS NULL;
