-- Turnos, locks y auditoría orquestador (BD_LANGLAB + BD_LAB)

CREATE SCHEMA IF NOT EXISTS "BD_LANGLAB";
CREATE SCHEMA IF NOT EXISTS "BD_LANGLAB";

ALTER TABLE "BD_LANGLAB"."CONVERSACION_TURNO"
	ADD COLUMN IF NOT EXISTS "ITURNINDEX" INT,
	ADD COLUMN IF NOT EXISTS "ILEASE" UUID,
	ADD COLUMN IF NOT EXISTS "PROVIDER" TEXT,
	ADD COLUMN IF NOT EXISTS "KEYLABEL" TEXT;

CREATE UNIQUE INDEX IF NOT EXISTS "UX_CONVERSACION_TURNO_INDEX"
	ON "BD_LANGLAB"."CONVERSACION_TURNO" ("ICONVERSACION", "ITURNINDEX")
	WHERE "ITURNINDEX" IS NOT NULL;

CREATE TABLE IF NOT EXISTS "BD_LANGLAB"."CONVERSACION_TURNOLOCK" (
	"ICONVERSACION" BIGINT PRIMARY KEY,
	"LOCKEDAT" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	"LOCKEDUNTIL" TIMESTAMPTZ NOT NULL DEFAULT (NOW() + INTERVAL '4 minutes'),
	"HOLDER" TEXT NOT NULL DEFAULT 'lab-langgraph',
	"META" JSONB NOT NULL DEFAULT '{}'
);

CREATE INDEX IF NOT EXISTS "IX_CONVERSACION_TURNOLOCK_UNTIL"
	ON "BD_LANGLAB"."CONVERSACION_TURNOLOCK" ("LOCKEDUNTIL");

CREATE TABLE IF NOT EXISTS "BD_LANGLAB"."ORCHESTRATOR_CAPABILITY" (
	"CAPABILITY" TEXT PRIMARY KEY,
	"MINTURNGAPMS" INT NOT NULL DEFAULT 0,
	"MAXLEASEMINUTES" INT NOT NULL DEFAULT 45,
	"MAXCONCURRENTLEASES" INT NOT NULL DEFAULT 12,
	"FHULTACT" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO "BD_LANGLAB"."ORCHESTRATOR_CAPABILITY" ("CAPABILITY", "MINTURNGAPMS", "MAXLEASEMINUTES", "MAXCONCURRENTLEASES")
VALUES
	('chat', 300, 45, 12),
	('proofread', 0, 45, 8),
	('whisper', 15000, 45, 4),
	('embeddings', 0, 30, 6),
	('rerank', 0, 30, 6)
ON CONFLICT ("CAPABILITY") DO UPDATE SET
	"MINTURNGAPMS" = EXCLUDED."MINTURNGAPMS",
	"MAXLEASEMINUTES" = EXCLUDED."MAXLEASEMINUTES",
	"MAXCONCURRENTLEASES" = EXCLUDED."MAXCONCURRENTLEASES",
	"FHULTACT" = NOW();

CREATE TABLE IF NOT EXISTS "BD_LANGLAB"."ORCHESTRATOR_ROTATIONLOG" (
	"ILOG" BIGSERIAL PRIMARY KEY,
	"TS" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	"CAPABILITY" TEXT NOT NULL,
	"PROVIDER" TEXT NOT NULL,
	"KEYLABEL" TEXT NOT NULL,
	"ILEASE" UUID,
	"ICONVERSACION" BIGINT,
	"ITURNINDEX" INT,
	"EVENT" TEXT NOT NULL,
	"WAITMS" INT,
	"META" JSONB NOT NULL DEFAULT '{}'
);

CREATE INDEX IF NOT EXISTS "IX_ORCHESTRATOR_ROTATIONLOG_TS"
	ON "BD_LANGLAB"."ORCHESTRATOR_ROTATIONLOG" ("TS" DESC);

CREATE INDEX IF NOT EXISTS "IX_ORCHESTRATOR_ROTATIONLOG_CONV"
	ON "BD_LANGLAB"."ORCHESTRATOR_ROTATIONLOG" ("ICONVERSACION")
	WHERE "ICONVERSACION" IS NOT NULL;

CREATE TABLE IF NOT EXISTS "BD_LANGLAB"."CONVERSACION_TURNOTIMING" (
	"ICONVERSACION" BIGINT PRIMARY KEY,
	"LASTTURNAT" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	"LASTCAPABILITY" TEXT NOT NULL DEFAULT 'chat',
	"FHULTACT" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE OR REPLACE FUNCTION "BD_LANGLAB"."CONVERSACION_NEXTTURNINDEX"(p_iconversacion BIGINT)
RETURNS INT
LANGUAGE sql
STABLE
AS $$
	SELECT COALESCE(MAX("ITURNINDEX"), 0) + 1
	FROM "BD_LANGLAB"."CONVERSACION_TURNO"
	WHERE "ICONVERSACION" = p_iconversacion;
$$;

CREATE OR REPLACE FUNCTION "BD_LANGLAB"."ORCHESTRATOR_EXPIRESTALORCHESTRATORLEASES"()
RETURNS INT
LANGUAGE plpgsql
AS $$
DECLARE
	n INT;
BEGIN
	UPDATE "BD_LANGLAB"."ORCHESTRATOR_LEASE"
	SET
		"RELEASEDAT" = NOW(),
		"BOK" = FALSE,
		"LASTERROR" = COALESCE("LASTERROR", 'expired_stale_lease')
	WHERE "RELEASEDAT" IS NULL AND "EXPIRESAT" < NOW();

	GET DIAGNOSTICS n = ROW_COUNT;

	DELETE FROM "BD_LANGLAB"."CONVERSACION_TURNOLOCK"
	WHERE "LOCKEDUNTIL" < NOW();

	RETURN n;
END;
$$;
