CREATE SCHEMA IF NOT EXISTS "BD_LAB";

CREATE TABLE IF NOT EXISTS "BD_LAB"."LAB_APICATALOGMANIFEST" (
	"ID" TEXT PRIMARY KEY,
	"VERSION" INT NOT NULL,
	"GENERATEDAT" TIMESTAMPTZ NOT NULL DEFAULT now(),
	"SOURCE" TEXT NOT NULL DEFAULT 'bundled',
	"BODY" JSONB NOT NULL
);

COMMENT ON TABLE "BD_LAB"."LAB_APICATALOGMANIFEST" IS
	'Manifiesto Postman PatyIA/ClientesIS. Fuente runtime si API_CATALOG_SOURCE=postgres.';
