-- Entity store isa-doc / langlab → BD_LAB.ENTITY_ROW
-- Definición canónica: db/schema/_shared/entity_store_loose.sql

CREATE SCHEMA IF NOT EXISTS "BD_LANGLAB";

CREATE TABLE IF NOT EXISTS "BD_LANGLAB"."ENTITY_ROW" (
	"PROJECT" TEXT NOT NULL,
	"PAGE" TEXT NOT NULL,
	"ENTITY" TEXT NOT NULL,
	"IENTITYID" TEXT NOT NULL,
	"BODY" JSONB NOT NULL DEFAULT '{}',
	"PARENTPROJECT" TEXT,
	"PARENTPAGE" TEXT,
	"PARENTENTITY" TEXT,
	"IPARENTENTITYID" TEXT,
	"SORTKEY" INT NOT NULL DEFAULT 0,
	"TAGS" TEXT[] NOT NULL DEFAULT '{}',
	"FHCRE" TIMESTAMPTZ NOT NULL DEFAULT now(),
	"FHULTACT" TIMESTAMPTZ NOT NULL DEFAULT now(),
	PRIMARY KEY ("PROJECT", "PAGE", "ENTITY", "IENTITYID")
);

CREATE INDEX IF NOT EXISTS "IX_ENTITY_ROW_SEGMENT" ON "BD_LANGLAB"."ENTITY_ROW" ("PROJECT", "PAGE", "ENTITY");
CREATE INDEX IF NOT EXISTS "IX_ENTITY_ROW_PARENT" ON "BD_LANGLAB"."ENTITY_ROW" ("PARENTPROJECT", "PARENTPAGE", "PARENTENTITY", "IPARENTENTITYID") WHERE "IPARENTENTITYID" IS NOT NULL;
CREATE INDEX IF NOT EXISTS "IX_ENTITY_ROW_TAGS" ON "BD_LANGLAB"."ENTITY_ROW" USING gin ("TAGS");
