CREATE SCHEMA IF NOT EXISTS "BD_LAB";

CREATE SEQUENCE IF NOT EXISTS "BD_LAB"."SEQ_STORE_STOREPROJECT" AS bigint START 1;
CREATE SEQUENCE IF NOT EXISTS "BD_LAB"."SEQ_STORE_STORESECTION" AS bigint START 1;
CREATE SEQUENCE IF NOT EXISTS "BD_LAB"."SEQ_ENTITY_ENTITYDEFINITION" AS bigint START 1;

CREATE TABLE IF NOT EXISTS "BD_LAB"."STORE_STOREPROJECT" (
	"IID" BIGINT PRIMARY KEY DEFAULT nextval('"BD_LAB"."SEQ_STORE_STOREPROJECT"'),
	"SLUG" TEXT NOT NULL UNIQUE,
	"NAME" TEXT NOT NULL,
	"DESCRIPTION" TEXT,
	"SORTKEY" INT NOT NULL DEFAULT 0,
	"META" JSONB NOT NULL DEFAULT '{}',
	"FHCRE" TIMESTAMPTZ NOT NULL DEFAULT now(),
	"FHULTACT" TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "BD_LAB"."STORE_STORESECTION" (
	"IID" BIGINT PRIMARY KEY DEFAULT nextval('"BD_LAB"."SEQ_STORE_STORESECTION"'),
	"PROJECTSLUG" TEXT NOT NULL,
	"SLUG" TEXT NOT NULL,
	"NAME" TEXT NOT NULL,
	"DESCRIPTION" TEXT,
	"SORTKEY" INT NOT NULL DEFAULT 0,
	"META" JSONB NOT NULL DEFAULT '{}',
	"FHCRE" TIMESTAMPTZ NOT NULL DEFAULT now(),
	"FHULTACT" TIMESTAMPTZ NOT NULL DEFAULT now(),
	UNIQUE ("PROJECTSLUG", "SLUG")
);

CREATE TABLE IF NOT EXISTS "BD_LAB"."ENTITY_ENTITYDEFINITION" (
	"IID" BIGINT PRIMARY KEY DEFAULT nextval('"BD_LAB"."SEQ_ENTITY_ENTITYDEFINITION"'),
	"PROJECTSLUG" TEXT NOT NULL,
	"SECTIONSLUG" TEXT NOT NULL,
	"ENTITYSLUG" TEXT NOT NULL,
	"NAME" TEXT NOT NULL,
	"DESCRIPTION" TEXT,
	"PRIMARYKEYS" JSONB NOT NULL,
	"COLUMNS" JSONB NOT NULL,
	"DETAILS" JSONB NOT NULL DEFAULT '[]',
	"SEARCHFIELDS" JSONB NOT NULL DEFAULT '[]',
	"SORTKEY" INT NOT NULL DEFAULT 0,
	"META" JSONB NOT NULL DEFAULT '{}',
	"FHCRE" TIMESTAMPTZ NOT NULL DEFAULT now(),
	"FHULTACT" TIMESTAMPTZ NOT NULL DEFAULT now(),
	UNIQUE ("PROJECTSLUG", "SECTIONSLUG", "ENTITYSLUG")
);

CREATE INDEX IF NOT EXISTS "IX_ENTITY_ENTITYDEFINITION_SEGMENT" ON "BD_LAB"."ENTITY_ENTITYDEFINITION" ("PROJECTSLUG", "SECTIONSLUG");
