CREATE SCHEMA IF NOT EXISTS "BD_LAB";

CREATE TABLE IF NOT EXISTS "BD_LAB"."BITACORA_BITACORAREVISADO" (
	"REVISADOKEY" TEXT PRIMARY KEY,
	"BCHECKED" BOOLEAN NOT NULL DEFAULT false,
	"FHULTACT" TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS "IX_BITACORA_BITACORAREVISADO_CHECKED"
	ON "BD_LAB"."BITACORA_BITACORAREVISADO" ("BCHECKED")
	WHERE "BCHECKED" = true;
