-- Usuarios lab-langgraph (JWT). Contraseñas solo como hash bcrypt.
CREATE SCHEMA IF NOT EXISTS "BD_LANGLAB";

CREATE TABLE IF NOT EXISTS "BD_LANGLAB"."AUTH_AUTHUSER" (
	"USERNAME" TEXT PRIMARY KEY,
	"PASSWORDHASH" TEXT NOT NULL,
	"DISPLAYNAME" TEXT,
	"ACTIVE" BOOLEAN NOT NULL DEFAULT true,
	"FHCRE" TIMESTAMPTZ NOT NULL DEFAULT now(),
	"FHULTACT" TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS "IX_AUTH_AUTHUSER_ACTIVE" ON "BD_LANGLAB"."AUTH_AUTHUSER" ("USERNAME") WHERE "ACTIVE" = true;
