-- Meta JSON por turno + funciones PG (BD_LANGLAB)

CREATE SCHEMA IF NOT EXISTS "BD_LANGLAB";
CREATE SCHEMA IF NOT EXISTS "BD_LANGLAB";

ALTER TABLE "BD_LANGLAB"."CONVERSACION_TURNO"
	ADD COLUMN IF NOT EXISTS "METALOG" JSONB NOT NULL DEFAULT '{}';

CREATE OR REPLACE FUNCTION "BD_LANGLAB"."CONVERSACION_NEXTTURNINDEX"(p_iconversacion BIGINT)
RETURNS INT LANGUAGE sql STABLE AS $$
	SELECT COALESCE(MAX("ITURNINDEX"), 0) + 1
	FROM "BD_LANGLAB"."CONVERSACION_TURNO"
	WHERE "ICONVERSACION" = p_iconversacion;
$$;

CREATE OR REPLACE FUNCTION "BD_LANGLAB"."ORCHESTRATOR_EXPIRESTALORCHESTRATORLEASES"()
RETURNS INT LANGUAGE plpgsql AS $$
DECLARE n INT;
BEGIN
	UPDATE "BD_LANGLAB"."ORCHESTRATOR_LEASE"
	SET "RELEASEDAT" = NOW(), "BOK" = FALSE,
		"LASTERROR" = COALESCE("LASTERROR", 'expired_stale_lease')
	WHERE "RELEASEDAT" IS NULL AND "EXPIRESAT" < NOW();
	GET DIAGNOSTICS n = ROW_COUNT;
	DELETE FROM "BD_LANGLAB"."CONVERSACION_TURNOLOCK" WHERE "LOCKEDUNTIL" < NOW();
	RETURN n;
END;
$$;
