-- Meta JSON por turno + funciones PG con nomenclatura entidad (BD_PATY)

CREATE SCHEMA IF NOT EXISTS "BD_PATY";
CREATE SCHEMA IF NOT EXISTS "BD_LAB";

ALTER TABLE "BD_PATY"."CONVERSACION_CONVERSACIONTURNO"
	ADD COLUMN IF NOT EXISTS "METALOG" JSONB NOT NULL DEFAULT '{}';

CREATE OR REPLACE FUNCTION "BD_PATY"."CONVERSACION_NEXTTURNINDEX"(p_iconversacion BIGINT)
RETURNS INT LANGUAGE sql STABLE AS $$
	SELECT COALESCE(MAX("ITURNINDEX"), 0) + 1
	FROM "BD_PATY"."CONVERSACION_CONVERSACIONTURNO"
	WHERE "ICONVERSACION" = p_iconversacion;
$$;

CREATE OR REPLACE FUNCTION "BD_PATY"."ORCHESTRATOR_EXPIRESTALORCHESTRATORLEASES"()
RETURNS INT LANGUAGE plpgsql AS $$
DECLARE n INT;
BEGIN
	UPDATE "BD_LAB"."ORCHESTRATOR_ORCHESTRATORLEASE"
	SET "RELEASEDAT" = NOW(), "BOK" = FALSE,
		"LASTERROR" = COALESCE("LASTERROR", 'expired_stale_lease')
	WHERE "RELEASEDAT" IS NULL AND "EXPIRESAT" < NOW();
	GET DIAGNOSTICS n = ROW_COUNT;
	DELETE FROM "BD_PATY"."CONVERSACION_CONVERSACIONTURNOLOCK" WHERE "LOCKEDUNTIL" < NOW();
	RETURN n;
END;
$$;
