-- Restaura BD_PATY como almacén PostgreSQL de ISA-DOC (superseded por 021 → BD_ISADOC).
-- Idempotente: no-op si BD_ISADOC ya existe.

DO $$ BEGIN
	IF EXISTS (SELECT 1 FROM pg_namespace WHERE nspname = 'BD_ISADOC') THEN
		RETURN;
	END IF;
END $$;

CREATE SCHEMA IF NOT EXISTS "BD_PATY";

CREATE OR REPLACE FUNCTION "BD_PATY"."_move_rename_table"(
	p_from_schema TEXT, p_old_table TEXT, p_new_table TEXT
) RETURNS VOID LANGUAGE plpgsql AS $$
BEGIN
	IF NOT EXISTS (
		SELECT 1 FROM information_schema.tables
		WHERE table_schema = p_from_schema AND table_name = p_old_table
	) THEN
		RETURN;
	END IF;
	IF p_from_schema IS DISTINCT FROM 'BD_PATY' THEN
		IF EXISTS (
			SELECT 1 FROM information_schema.tables
			WHERE table_schema = 'BD_PATY' AND table_name = p_new_table
		) THEN
			EXECUTE format(
				'INSERT INTO "BD_PATY".%I SELECT * FROM %I.%I ON CONFLICT DO NOTHING',
				p_new_table, p_from_schema, p_old_table
			);
			EXECUTE format('DROP TABLE %I.%I', p_from_schema, p_old_table);
			RETURN;
		END IF;
		IF EXISTS (
			SELECT 1 FROM information_schema.tables
			WHERE table_schema = 'BD_PATY' AND table_name = p_old_table
		) THEN
			EXECUTE format('DROP TABLE %I.%I', p_from_schema, p_old_table);
			RETURN;
		END IF;
		EXECUTE format('ALTER TABLE %I.%I SET SCHEMA "BD_PATY"', p_from_schema, p_old_table);
	END IF;
	IF p_old_table IS DISTINCT FROM p_new_table THEN
		IF EXISTS (
			SELECT 1 FROM information_schema.tables
			WHERE table_schema = 'BD_PATY' AND table_name = p_old_table
		) AND EXISTS (
			SELECT 1 FROM information_schema.tables
			WHERE table_schema = 'BD_PATY' AND table_name = p_new_table
		) THEN
			EXECUTE format(
				'INSERT INTO "BD_PATY".%I SELECT * FROM "BD_PATY".%I ON CONFLICT DO NOTHING',
				p_new_table, p_old_table
			);
			EXECUTE format('DROP TABLE "BD_PATY".%I', p_old_table);
		ELSIF EXISTS (
			SELECT 1 FROM information_schema.tables
			WHERE table_schema = 'BD_PATY' AND table_name = p_old_table
		) AND NOT EXISTS (
			SELECT 1 FROM information_schema.tables
			WHERE table_schema = 'BD_PATY' AND table_name = p_new_table
		) THEN
			EXECUTE format('ALTER TABLE "BD_PATY".%I RENAME TO %I', p_old_table, p_new_table);
		END IF;
	END IF;
END;
$$;

CREATE OR REPLACE FUNCTION "BD_PATY"."_move_rename_sequence"(
	p_from_schema TEXT, p_old_seq TEXT, p_new_seq TEXT
) RETURNS VOID LANGUAGE plpgsql AS $$
BEGIN
	IF NOT EXISTS (
		SELECT 1 FROM pg_sequences
		WHERE schemaname = p_from_schema AND sequencename = p_old_seq
	) THEN
		RETURN;
	END IF;
	IF p_from_schema IS DISTINCT FROM 'BD_PATY' THEN
		IF EXISTS (
			SELECT 1 FROM pg_sequences
			WHERE schemaname = 'BD_PATY' AND sequencename = p_new_seq
		) THEN
			RETURN;
		END IF;
		EXECUTE format('ALTER SEQUENCE %I.%I SET SCHEMA "BD_PATY"', p_from_schema, p_old_seq);
	END IF;
	IF p_old_seq IS DISTINCT FROM p_new_seq
	   AND EXISTS (SELECT 1 FROM pg_sequences WHERE schemaname = 'BD_PATY' AND sequencename = p_old_seq)
	   AND NOT EXISTS (SELECT 1 FROM pg_sequences WHERE schemaname = 'BD_PATY' AND sequencename = p_new_seq) THEN
		EXECUTE format('ALTER SEQUENCE "BD_PATY".%I RENAME TO %I', p_old_seq, p_new_seq);
	END IF;
END;
$$;

DO $$
BEGIN
	IF EXISTS (SELECT 1 FROM pg_namespace WHERE nspname = 'BD_ISADOC') THEN
		RETURN;
	END IF;
	-- Entity store ISA-DOC
	PERFORM "BD_PATY"."_move_rename_table"('BD_LANGLAB', 'ENTITY_ROW', 'ENTITY_ROW');
	PERFORM "BD_PATY"."_move_rename_table"('BD_LANGLAB', 'ENTITY_ENTITYROW', 'ENTITY_ROW');
	PERFORM "BD_PATY"."_move_rename_table"('BD_LAB', 'ENTITY_ROW', 'ENTITY_ROW');
	PERFORM "BD_PATY"."_move_rename_table"('BD_LAB', 'ENTITY_ENTITYROW', 'ENTITY_ROW');
	PERFORM "BD_PATY"."_move_rename_table"('BD_LAB', 'lab_entity_row', 'ENTITY_ROW');

	-- Catálogo store
	PERFORM "BD_PATY"."_move_rename_sequence"('BD_LANGLAB', 'SEQ_STORE_STOREPROJECT', 'SEQ_STORE_PROJECT');
	PERFORM "BD_PATY"."_move_rename_sequence"('BD_LANGLAB', 'SEQ_STORE_PROJECT', 'SEQ_STORE_PROJECT');
	PERFORM "BD_PATY"."_move_rename_sequence"('BD_LANGLAB', 'SEQ_STORE_STORESECTION', 'SEQ_STORE_SECTION');
	PERFORM "BD_PATY"."_move_rename_sequence"('BD_LANGLAB', 'SEQ_STORE_SECTION', 'SEQ_STORE_SECTION');
	PERFORM "BD_PATY"."_move_rename_sequence"('BD_LANGLAB', 'SEQ_ENTITY_ENTITYDEFINITION', 'SEQ_ENTITY_DEFINITION');
	PERFORM "BD_PATY"."_move_rename_sequence"('BD_LANGLAB', 'SEQ_ENTITY_DEFINITION', 'SEQ_ENTITY_DEFINITION');

	PERFORM "BD_PATY"."_move_rename_table"('BD_LANGLAB', 'STORE_STOREPROJECT', 'STORE_PROJECT');
	PERFORM "BD_PATY"."_move_rename_table"('BD_LANGLAB', 'STORE_PROJECT', 'STORE_PROJECT');
	PERFORM "BD_PATY"."_move_rename_table"('BD_LANGLAB', 'STORE_STORESECTION', 'STORE_SECTION');
	PERFORM "BD_PATY"."_move_rename_table"('BD_LANGLAB', 'STORE_SECTION', 'STORE_SECTION');
	PERFORM "BD_PATY"."_move_rename_table"('BD_LANGLAB', 'ENTITY_ENTITYDEFINITION', 'ENTITY_DEFINITION');
	PERFORM "BD_PATY"."_move_rename_table"('BD_LANGLAB', 'ENTITY_DEFINITION', 'ENTITY_DEFINITION');

	-- Bitácora revisado + Postman manifest
	PERFORM "BD_PATY"."_move_rename_table"('BD_LANGLAB', 'BITACORA_BITACORAREVISADO', 'BITACORA_REVISADO');
	PERFORM "BD_PATY"."_move_rename_table"('BD_LANGLAB', 'BITACORA_REVISADO', 'BITACORA_REVISADO');
	PERFORM "BD_PATY"."_move_rename_table"('BD_LANGLAB', 'APICATALOG_APICATALOGMANIFEST', 'APICATALOG_MANIFEST');
	PERFORM "BD_PATY"."_move_rename_table"('BD_LANGLAB', 'APICATALOG_MANIFEST', 'APICATALOG_MANIFEST');
END;
$$;

-- DDL canónico en BD_PATY (si no existía tras migración)
CREATE SEQUENCE IF NOT EXISTS "BD_PATY"."SEQ_STORE_PROJECT" AS bigint START 1;
CREATE SEQUENCE IF NOT EXISTS "BD_PATY"."SEQ_STORE_SECTION" AS bigint START 1;
CREATE SEQUENCE IF NOT EXISTS "BD_PATY"."SEQ_ENTITY_DEFINITION" AS bigint START 1;

CREATE TABLE IF NOT EXISTS "BD_PATY"."ENTITY_ROW" (
	"PROJECT" TEXT NOT NULL,
	"PAGE" TEXT NOT NULL,
	"ENTITY" TEXT NOT NULL,
	"IENTITYID" TEXT NOT NULL,
	"BODY" JSONB NOT NULL DEFAULT '{}',
	"PARENTPROJECT" TEXT,
	"PARENTPAGE" TEXT,
	"PARENTENTITY" TEXT,
	"IPARENTENTITYID" TEXT,
	"SORTKEY" INT NOT NULL DEFAULT 0,
	"TAGS" TEXT[] NOT NULL DEFAULT '{}',
	"FHCRE" TIMESTAMPTZ NOT NULL DEFAULT now(),
	"FHULTACT" TIMESTAMPTZ NOT NULL DEFAULT now(),
	PRIMARY KEY ("PROJECT", "PAGE", "ENTITY", "IENTITYID")
);

CREATE TABLE IF NOT EXISTS "BD_PATY"."STORE_PROJECT" (
	"IID" BIGINT PRIMARY KEY DEFAULT nextval('"BD_PATY"."SEQ_STORE_PROJECT"'),
	"SLUG" TEXT NOT NULL UNIQUE,
	"NAME" TEXT NOT NULL,
	"DESCRIPTION" TEXT,
	"SORTKEY" INT NOT NULL DEFAULT 0,
	"META" JSONB NOT NULL DEFAULT '{}',
	"FHCRE" TIMESTAMPTZ NOT NULL DEFAULT now(),
	"FHULTACT" TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "BD_PATY"."STORE_SECTION" (
	"IID" BIGINT PRIMARY KEY DEFAULT nextval('"BD_PATY"."SEQ_STORE_SECTION"'),
	"PROJECTSLUG" TEXT NOT NULL,
	"SLUG" TEXT NOT NULL,
	"NAME" TEXT NOT NULL,
	"DESCRIPTION" TEXT,
	"SORTKEY" INT NOT NULL DEFAULT 0,
	"META" JSONB NOT NULL DEFAULT '{}',
	"FHCRE" TIMESTAMPTZ NOT NULL DEFAULT now(),
	"FHULTACT" TIMESTAMPTZ NOT NULL DEFAULT now(),
	UNIQUE ("PROJECTSLUG", "SLUG")
);

CREATE TABLE IF NOT EXISTS "BD_PATY"."ENTITY_DEFINITION" (
	"IID" BIGINT PRIMARY KEY DEFAULT nextval('"BD_PATY"."SEQ_ENTITY_DEFINITION"'),
	"PROJECTSLUG" TEXT NOT NULL,
	"SECTIONSLUG" TEXT NOT NULL,
	"ENTITYSLUG" TEXT NOT NULL,
	"NAME" TEXT NOT NULL,
	"DESCRIPTION" TEXT,
	"PRIMARYKEYS" JSONB NOT NULL,
	"COLUMNS" JSONB NOT NULL,
	"DETAILS" JSONB NOT NULL DEFAULT '[]',
	"SEARCHFIELDS" JSONB NOT NULL DEFAULT '[]',
	"SORTKEY" INT NOT NULL DEFAULT 0,
	"META" JSONB NOT NULL DEFAULT '{}',
	"FHCRE" TIMESTAMPTZ NOT NULL DEFAULT now(),
	"FHULTACT" TIMESTAMPTZ NOT NULL DEFAULT now(),
	UNIQUE ("PROJECTSLUG", "SECTIONSLUG", "ENTITYSLUG")
);

CREATE TABLE IF NOT EXISTS "BD_PATY"."BITACORA_REVISADO" (
	"REVISADOKEY" TEXT PRIMARY KEY,
	"BCHECKED" BOOLEAN NOT NULL DEFAULT false,
	"FHULTACT" TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "BD_PATY"."APICATALOG_MANIFEST" (
	"ID" TEXT PRIMARY KEY,
	"VERSION" INT NOT NULL,
	"GENERATEDAT" TIMESTAMPTZ NOT NULL DEFAULT now(),
	"SOURCE" TEXT NOT NULL DEFAULT 'bundled',
	"BODY" JSONB NOT NULL
);

CREATE INDEX IF NOT EXISTS "IX_ENTITY_ROW_SEGMENT" ON "BD_PATY"."ENTITY_ROW" ("PROJECT", "PAGE", "ENTITY");
CREATE INDEX IF NOT EXISTS "IX_ENTITY_ROW_PARENT" ON "BD_PATY"."ENTITY_ROW" ("PARENTPROJECT", "PARENTPAGE", "PARENTENTITY", "IPARENTENTITYID") WHERE "IPARENTENTITYID" IS NOT NULL;
CREATE INDEX IF NOT EXISTS "IX_ENTITY_ROW_TAGS" ON "BD_PATY"."ENTITY_ROW" USING gin ("TAGS");
CREATE INDEX IF NOT EXISTS "IX_ENTITY_DEFINITION_SEGMENT" ON "BD_PATY"."ENTITY_DEFINITION" ("PROJECTSLUG", "SECTIONSLUG");
CREATE INDEX IF NOT EXISTS "IX_BITACORA_REVISADO_CHECKED" ON "BD_PATY"."BITACORA_REVISADO" ("BCHECKED") WHERE "BCHECKED" = true;

DROP FUNCTION IF EXISTS "BD_PATY"."_move_rename_table"(TEXT, TEXT, TEXT);
DROP FUNCTION IF EXISTS "BD_PATY"."_move_rename_sequence"(TEXT, TEXT, TEXT);

COMMENT ON SCHEMA "BD_PATY" IS 'ISA-DOC / PatyIA administración: entity store, tickets, revisado, catálogo Postman.';
