-- Unifica BD_PATY + BD_CLIENTESIS → BD_ISADOC (único almacén PostgreSQL de ISA-DOC).

DO $$ BEGIN
	IF EXISTS (SELECT 1 FROM pg_namespace WHERE nspname = 'BD_ISADOC')
	   AND NOT EXISTS (SELECT 1 FROM pg_namespace WHERE nspname = 'BD_PATY')
	   AND NOT EXISTS (SELECT 1 FROM pg_namespace WHERE nspname = 'BD_CLIENTESIS') THEN
		RETURN;
	END IF;
END $$;

CREATE SCHEMA IF NOT EXISTS "BD_ISADOC";

CREATE OR REPLACE FUNCTION "BD_ISADOC"."_absorb_table"(
	p_from_schema TEXT, p_table TEXT
) RETURNS VOID LANGUAGE plpgsql AS $$
BEGIN
	IF NOT EXISTS (
		SELECT 1 FROM information_schema.tables
		WHERE table_schema = p_from_schema AND table_name = p_table
	) THEN
		RETURN;
	END IF;
	IF p_from_schema = 'BD_ISADOC' THEN
		RETURN;
	END IF;
	IF NOT EXISTS (
		SELECT 1 FROM information_schema.tables
		WHERE table_schema = 'BD_ISADOC' AND table_name = p_table
	) THEN
		BEGIN
			EXECUTE format('ALTER TABLE %I.%I SET SCHEMA "BD_ISADOC"', p_from_schema, p_table);
		EXCEPTION WHEN duplicate_object THEN
			NULL;
		END;
		RETURN;
	END IF;
	IF p_table = 'ENTITY_ROW' THEN
		EXECUTE format(
			'INSERT INTO "BD_ISADOC"."ENTITY_ROW" SELECT * FROM %I.%I ON CONFLICT DO NOTHING',
			p_from_schema, p_table
		);
	ELSE
		EXECUTE format(
			'INSERT INTO "BD_ISADOC".%I SELECT * FROM %I.%I ON CONFLICT DO NOTHING',
			p_table, p_from_schema, p_table
		);
	END IF;
	EXECUTE format('DROP TABLE %I.%I', p_from_schema, p_table);
END;
$$;

CREATE OR REPLACE FUNCTION "BD_ISADOC"."_absorb_sequence"(
	p_from_schema TEXT, p_seq TEXT
) RETURNS VOID LANGUAGE plpgsql AS $$
BEGIN
	IF NOT EXISTS (SELECT 1 FROM pg_sequences WHERE schemaname = p_from_schema AND sequencename = p_seq) THEN
		RETURN;
	END IF;
	IF p_from_schema = 'BD_ISADOC' THEN RETURN; END IF;
	IF NOT EXISTS (SELECT 1 FROM pg_sequences WHERE schemaname = 'BD_ISADOC' AND sequencename = p_seq) THEN
		EXECUTE format('ALTER SEQUENCE %I.%I SET SCHEMA "BD_ISADOC"', p_from_schema, p_seq);
	END IF;
END;
$$;

DO $$
DECLARE
	src TEXT;
	tables TEXT[] := ARRAY[
		'ENTITY_ROW', 'STORE_PROJECT', 'STORE_SECTION', 'ENTITY_DEFINITION',
		'BITACORA_REVISADO', 'APICATALOG_MANIFEST',
		'STORE_STOREPROJECT', 'STORE_STORESECTION', 'ENTITY_ENTITYDEFINITION',
		'BITACORA_BITACORAREVISADO', 'APICATALOG_APICATALOGMANIFEST', 'ENTITY_ENTITYROW'
	];
	seqs TEXT[] := ARRAY[
		'SEQ_STORE_PROJECT', 'SEQ_STORE_SECTION', 'SEQ_ENTITY_DEFINITION',
		'SEQ_STORE_STOREPROJECT', 'SEQ_STORE_STORESECTION', 'SEQ_ENTITY_ENTITYDEFINITION'
	];
	langlab_orphans TEXT[] := ARRAY[
		'STORE_STOREPROJECT', 'STORE_STORESECTION', 'ENTITY_ENTITYDEFINITION',
		'BITACORA_BITACORAREVISADO', 'APICATALOG_APICATALOGMANIFEST', 'ENTITY_ENTITYROW',
		'ENTITY_ROW', 'STORE_PROJECT', 'STORE_SECTION', 'ENTITY_DEFINITION',
		'BITACORA_REVISADO', 'APICATALOG_MANIFEST'
	];
	t TEXT;
	s TEXT;
BEGIN
	-- Siempre absorber BD_PATY / BD_CLIENTESIS aunque BD_ISADOC ya exista.
	FOREACH src IN ARRAY ARRAY['BD_PATY', 'BD_CLIENTESIS', 'BD_LANGLAB'] LOOP
		IF NOT EXISTS (SELECT 1 FROM pg_namespace WHERE nspname = src) THEN CONTINUE; END IF;
		FOREACH t IN ARRAY tables LOOP
			PERFORM "BD_ISADOC"."_absorb_table"(src, t);
		END LOOP;
		FOREACH s IN ARRAY seqs LOOP
			PERFORM "BD_ISADOC"."_absorb_sequence"(src, s);
		END LOOP;
	END LOOP;

	FOREACH t IN ARRAY langlab_orphans LOOP
		IF EXISTS (SELECT 1 FROM pg_tables WHERE schemaname = 'BD_LANGLAB' AND tablename = t) THEN
			EXECUTE format('DROP TABLE "BD_LANGLAB".%I', t);
		END IF;
	END LOOP;
END;
$$;

-- Renombres sin depender de función de 020
DO $$
BEGIN
	IF EXISTS (SELECT 1 FROM pg_tables WHERE schemaname='BD_ISADOC' AND tablename='STORE_STOREPROJECT')
	   AND NOT EXISTS (SELECT 1 FROM pg_tables WHERE schemaname='BD_ISADOC' AND tablename='STORE_PROJECT') THEN
		ALTER TABLE "BD_ISADOC"."STORE_STOREPROJECT" RENAME TO "STORE_PROJECT";
	END IF;
	IF EXISTS (SELECT 1 FROM pg_tables WHERE schemaname='BD_ISADOC' AND tablename='STORE_STORESECTION')
	   AND NOT EXISTS (SELECT 1 FROM pg_tables WHERE schemaname='BD_ISADOC' AND tablename='STORE_SECTION') THEN
		ALTER TABLE "BD_ISADOC"."STORE_STORESECTION" RENAME TO "STORE_SECTION";
	END IF;
	IF EXISTS (SELECT 1 FROM pg_tables WHERE schemaname='BD_ISADOC' AND tablename='ENTITY_ENTITYDEFINITION')
	   AND NOT EXISTS (SELECT 1 FROM pg_tables WHERE schemaname='BD_ISADOC' AND tablename='ENTITY_DEFINITION') THEN
		ALTER TABLE "BD_ISADOC"."ENTITY_ENTITYDEFINITION" RENAME TO "ENTITY_DEFINITION";
	END IF;
	IF EXISTS (SELECT 1 FROM pg_tables WHERE schemaname='BD_ISADOC' AND tablename='BITACORA_BITACORAREVISADO')
	   AND NOT EXISTS (SELECT 1 FROM pg_tables WHERE schemaname='BD_ISADOC' AND tablename='BITACORA_REVISADO') THEN
		ALTER TABLE "BD_ISADOC"."BITACORA_BITACORAREVISADO" RENAME TO "BITACORA_REVISADO";
	END IF;
	IF EXISTS (SELECT 1 FROM pg_tables WHERE schemaname='BD_ISADOC' AND tablename='APICATALOG_APICATALOGMANIFEST')
	   AND NOT EXISTS (SELECT 1 FROM pg_tables WHERE schemaname='BD_ISADOC' AND tablename='APICATALOG_MANIFEST') THEN
		ALTER TABLE "BD_ISADOC"."APICATALOG_APICATALOGMANIFEST" RENAME TO "APICATALOG_MANIFEST";
	END IF;
	IF EXISTS (SELECT 1 FROM pg_tables WHERE schemaname='BD_ISADOC' AND tablename='ENTITY_ENTITYROW')
	   AND NOT EXISTS (SELECT 1 FROM pg_tables WHERE schemaname='BD_ISADOC' AND tablename='ENTITY_ROW') THEN
		ALTER TABLE "BD_ISADOC"."ENTITY_ENTITYROW" RENAME TO "ENTITY_ROW";
	END IF;
END;
$$;

-- DDL canónico
CREATE SEQUENCE IF NOT EXISTS "BD_ISADOC"."SEQ_STORE_PROJECT" AS bigint START 1;
CREATE SEQUENCE IF NOT EXISTS "BD_ISADOC"."SEQ_STORE_SECTION" AS bigint START 1;
CREATE SEQUENCE IF NOT EXISTS "BD_ISADOC"."SEQ_ENTITY_DEFINITION" AS bigint START 1;

CREATE TABLE IF NOT EXISTS "BD_ISADOC"."ENTITY_ROW" (
	"PROJECT" TEXT NOT NULL,
	"PAGE" TEXT NOT NULL,
	"ENTITY" TEXT NOT NULL,
	"IENTITYID" TEXT NOT NULL,
	"BODY" JSONB NOT NULL DEFAULT '{}',
	"PARENTPROJECT" TEXT,
	"PARENTPAGE" TEXT,
	"PARENTENTITY" TEXT,
	"IPARENTENTITYID" TEXT,
	"SORTKEY" INT NOT NULL DEFAULT 0,
	"TAGS" TEXT[] NOT NULL DEFAULT '{}',
	"FHCRE" TIMESTAMPTZ NOT NULL DEFAULT now(),
	"FHULTACT" TIMESTAMPTZ NOT NULL DEFAULT now(),
	PRIMARY KEY ("PROJECT", "PAGE", "ENTITY", "IENTITYID")
);

CREATE TABLE IF NOT EXISTS "BD_ISADOC"."STORE_PROJECT" (
	"IID" BIGINT PRIMARY KEY DEFAULT nextval('"BD_ISADOC"."SEQ_STORE_PROJECT"'),
	"SLUG" TEXT NOT NULL UNIQUE,
	"NAME" TEXT NOT NULL,
	"DESCRIPTION" TEXT,
	"SORTKEY" INT NOT NULL DEFAULT 0,
	"META" JSONB NOT NULL DEFAULT '{}',
	"FHCRE" TIMESTAMPTZ NOT NULL DEFAULT now(),
	"FHULTACT" TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "BD_ISADOC"."STORE_SECTION" (
	"IID" BIGINT PRIMARY KEY DEFAULT nextval('"BD_ISADOC"."SEQ_STORE_SECTION"'),
	"PROJECTSLUG" TEXT NOT NULL,
	"SLUG" TEXT NOT NULL,
	"NAME" TEXT NOT NULL,
	"DESCRIPTION" TEXT,
	"SORTKEY" INT NOT NULL DEFAULT 0,
	"META" JSONB NOT NULL DEFAULT '{}',
	"FHCRE" TIMESTAMPTZ NOT NULL DEFAULT now(),
	"FHULTACT" TIMESTAMPTZ NOT NULL DEFAULT now(),
	UNIQUE ("PROJECTSLUG", "SLUG")
);

CREATE TABLE IF NOT EXISTS "BD_ISADOC"."ENTITY_DEFINITION" (
	"IID" BIGINT PRIMARY KEY DEFAULT nextval('"BD_ISADOC"."SEQ_ENTITY_DEFINITION"'),
	"PROJECTSLUG" TEXT NOT NULL,
	"SECTIONSLUG" TEXT NOT NULL,
	"ENTITYSLUG" TEXT NOT NULL,
	"NAME" TEXT NOT NULL,
	"DESCRIPTION" TEXT,
	"PRIMARYKEYS" JSONB NOT NULL,
	"COLUMNS" JSONB NOT NULL,
	"DETAILS" JSONB NOT NULL DEFAULT '[]',
	"SEARCHFIELDS" JSONB NOT NULL DEFAULT '[]',
	"SORTKEY" INT NOT NULL DEFAULT 0,
	"META" JSONB NOT NULL DEFAULT '{}',
	"FHCRE" TIMESTAMPTZ NOT NULL DEFAULT now(),
	"FHULTACT" TIMESTAMPTZ NOT NULL DEFAULT now(),
	UNIQUE ("PROJECTSLUG", "SECTIONSLUG", "ENTITYSLUG")
);

CREATE TABLE IF NOT EXISTS "BD_ISADOC"."BITACORA_REVISADO" (
	"REVISADOKEY" TEXT PRIMARY KEY,
	"BCHECKED" BOOLEAN NOT NULL DEFAULT false,
	"FHULTACT" TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "BD_ISADOC"."APICATALOG_MANIFEST" (
	"ID" TEXT PRIMARY KEY,
	"VERSION" INT NOT NULL,
	"GENERATEDAT" TIMESTAMPTZ NOT NULL DEFAULT now(),
	"SOURCE" TEXT NOT NULL DEFAULT 'bundled',
	"BODY" JSONB NOT NULL
);

CREATE INDEX IF NOT EXISTS "IX_ENTITY_ROW_SEGMENT" ON "BD_ISADOC"."ENTITY_ROW" ("PROJECT", "PAGE", "ENTITY");
CREATE INDEX IF NOT EXISTS "IX_ENTITY_ROW_PARENT" ON "BD_ISADOC"."ENTITY_ROW" ("PARENTPROJECT", "PARENTPAGE", "PARENTENTITY", "IPARENTENTITYID") WHERE "IPARENTENTITYID" IS NOT NULL;
CREATE INDEX IF NOT EXISTS "IX_ENTITY_ROW_TAGS" ON "BD_ISADOC"."ENTITY_ROW" USING gin ("TAGS");

DROP FUNCTION IF EXISTS "BD_ISADOC"."_absorb_table"(TEXT, TEXT);
DROP FUNCTION IF EXISTS "BD_ISADOC"."_absorb_sequence"(TEXT, TEXT);

DROP SCHEMA IF EXISTS "BD_PATY" CASCADE;
DROP SCHEMA IF EXISTS "BD_CLIENTESIS" CASCADE;

COMMENT ON SCHEMA "BD_ISADOC" IS 'ISA-DOC: entity store, tickets, revisado, catálogo (PatyIA + ClientesIS PG).';
