-- CONVERSACION_MENSAJECALIFICADO → CONVERSACION_MENSAJE + CONVERSACION_MENSAJE_METRICAS
-- Mensajes input/output en MENSAJE; tokens, latencia, calificación en METRICAS.

CREATE SCHEMA IF NOT EXISTS "BD_LANGLAB";

DO $$
BEGIN
	IF EXISTS (
		SELECT 1 FROM pg_tables
		WHERE schemaname = 'BD_LANGLAB' AND tablename = 'CONVERSACION_MENSAJECALIFICADO'
	) AND NOT EXISTS (
		SELECT 1 FROM pg_tables
		WHERE schemaname = 'BD_LANGLAB' AND tablename = 'CONVERSACION_MENSAJE'
	) THEN
		ALTER TABLE "BD_LANGLAB"."CONVERSACION_MENSAJECALIFICADO" RENAME TO "CONVERSACION_MENSAJE";
	END IF;
END $$;

CREATE TABLE IF NOT EXISTS "BD_LANGLAB"."CONVERSACION_MENSAJE" (
	"IMENSAJE" BIGSERIAL PRIMARY KEY,
	"ICONVERSACION" BIGINT NOT NULL,
	"ITURNO" BIGINT,
	"IORDEN" INT NOT NULL DEFAULT 0,
	"DIRECCION" TEXT NOT NULL DEFAULT 'OUTPUT',
	"ROL" TEXT NOT NULL DEFAULT 'usuario',
	"CONTENIDO" TEXT NOT NULL DEFAULT '',
	"IREFERENCIA" BIGINT,
	"FHCRE" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE "BD_LANGLAB"."CONVERSACION_MENSAJE"
	ADD COLUMN IF NOT EXISTS "ITURNO" BIGINT,
	ADD COLUMN IF NOT EXISTS "IORDEN" INT NOT NULL DEFAULT 0,
	ADD COLUMN IF NOT EXISTS "DIRECCION" TEXT NOT NULL DEFAULT 'OUTPUT',
	ADD COLUMN IF NOT EXISTS "ROL" TEXT NOT NULL DEFAULT 'usuario';

CREATE TABLE IF NOT EXISTS "BD_LANGLAB"."CONVERSACION_MENSAJE_METRICAS" (
	"IMETRICA" BIGSERIAL PRIMARY KEY,
	"IMENSAJE" BIGINT NOT NULL,
	"ITURNO" BIGINT,
	"QTOKENSENTRADA" INT,
	"QTOKENSSALIDA" INT,
	"LATENCYMS" INT,
	"PROVIDER" TEXT,
	"MODELO" TEXT,
	"CALIFICACION" INT,
	"COMENTARIO" TEXT,
	"BUTIL" BOOLEAN,
	"META" JSONB NOT NULL DEFAULT '{}',
	"FHCRE" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	UNIQUE ("IMENSAJE")
);

CREATE INDEX IF NOT EXISTS "IX_CONVERSACION_MENSAJE_ICONVERSACION"
	ON "BD_LANGLAB"."CONVERSACION_MENSAJE" ("ICONVERSACION", "IORDEN");
CREATE INDEX IF NOT EXISTS "IX_CONVERSACION_MENSAJE_ITURNO"
	ON "BD_LANGLAB"."CONVERSACION_MENSAJE" ("ITURNO") WHERE "ITURNO" IS NOT NULL;
CREATE INDEX IF NOT EXISTS "IX_CONVERSACION_MENSAJE_METRICAS_IMENSAJE"
	ON "BD_LANGLAB"."CONVERSACION_MENSAJE_METRICAS" ("IMENSAJE");

-- Métricas legacy (calificación) desde columnas antiguas en MENSAJE
DO $$
BEGIN
	IF EXISTS (
		SELECT 1 FROM information_schema.columns
		WHERE table_schema = 'BD_LANGLAB' AND table_name = 'CONVERSACION_MENSAJE' AND column_name = 'CALIFICACION'
	) THEN
		INSERT INTO "BD_LANGLAB"."CONVERSACION_MENSAJE_METRICAS" (
			"IMENSAJE", "CALIFICACION", "COMENTARIO", "BUTIL", "FHCRE"
		)
		SELECT m."IMENSAJE", m."CALIFICACION", m."COMENTARIO", m."BUTIL", m."FHCRE"
		FROM "BD_LANGLAB"."CONVERSACION_MENSAJE" m
		WHERE (m."CALIFICACION" IS NOT NULL OR m."COMENTARIO" IS NOT NULL OR m."BUTIL" IS NOT NULL)
		  AND NOT EXISTS (
			SELECT 1 FROM "BD_LANGLAB"."CONVERSACION_MENSAJE_METRICAS" x WHERE x."IMENSAJE" = m."IMENSAJE"
		  );
		ALTER TABLE "BD_LANGLAB"."CONVERSACION_MENSAJE" DROP COLUMN IF EXISTS "CALIFICACION";
		ALTER TABLE "BD_LANGLAB"."CONVERSACION_MENSAJE" DROP COLUMN IF EXISTS "COMENTARIO";
		ALTER TABLE "BD_LANGLAB"."CONVERSACION_MENSAJE" DROP COLUMN IF EXISTS "BUTIL";
	END IF;
END $$;

-- Backfill input/output desde CONVERSACION_TURNO (idempotente por ITURNO)
INSERT INTO "BD_LANGLAB"."CONVERSACION_MENSAJE" (
	"ICONVERSACION", "ITURNO", "IORDEN", "DIRECCION", "ROL", "CONTENIDO", "FHCRE"
)
SELECT t."ICONVERSACION", t."ITURNO",
	COALESCE(t."ITURNINDEX", 0) * 2,
	'INPUT', 'usuario', t."PROMPTTEXT", t."TS"
FROM "BD_LANGLAB"."CONVERSACION_TURNO" t
WHERE NOT EXISTS (
	SELECT 1 FROM "BD_LANGLAB"."CONVERSACION_MENSAJE" m
	WHERE m."ITURNO" = t."ITURNO" AND m."DIRECCION" = 'INPUT'
);

INSERT INTO "BD_LANGLAB"."CONVERSACION_MENSAJE" (
	"ICONVERSACION", "ITURNO", "IORDEN", "DIRECCION", "ROL", "CONTENIDO", "IREFERENCIA", "FHCRE"
)
SELECT t."ICONVERSACION", t."ITURNO",
	COALESCE(t."ITURNINDEX", 0) * 2 + 1,
	'OUTPUT', 'asistente', t."RESPONSETEXT",
	(SELECT mi."IMENSAJE" FROM "BD_LANGLAB"."CONVERSACION_MENSAJE" mi
	 WHERE mi."ITURNO" = t."ITURNO" AND mi."DIRECCION" = 'INPUT' LIMIT 1),
	t."TS"
FROM "BD_LANGLAB"."CONVERSACION_TURNO" t
WHERE NOT EXISTS (
	SELECT 1 FROM "BD_LANGLAB"."CONVERSACION_MENSAJE" m
	WHERE m."ITURNO" = t."ITURNO" AND m."DIRECCION" = 'OUTPUT'
);

INSERT INTO "BD_LANGLAB"."CONVERSACION_MENSAJE_METRICAS" (
	"IMENSAJE", "ITURNO", "QTOKENSENTRADA", "QTOKENSSALIDA", "LATENCYMS", "PROVIDER", "MODELO", "META", "FHCRE"
)
SELECT mo."IMENSAJE", t."ITURNO",
	COALESCE((t."METALOG"->'classification'->>'tokensIn')::int, 0) + COALESCE((t."METALOG"->'agent'->>'tokensIn')::int, 0),
	COALESCE((t."METALOG"->'classification'->>'tokensOut')::int, 0) + COALESCE((t."METALOG"->'agent'->>'tokensOut')::int, 0),
	t."LATENCYMS", t."PROVIDER", NULL,
	COALESCE(t."METALOG", '{}'::jsonb), t."TS"
FROM "BD_LANGLAB"."CONVERSACION_TURNO" t
JOIN "BD_LANGLAB"."CONVERSACION_MENSAJE" mo
	ON mo."ITURNO" = t."ITURNO" AND mo."DIRECCION" = 'OUTPUT'
WHERE NOT EXISTS (
	SELECT 1 FROM "BD_LANGLAB"."CONVERSACION_MENSAJE_METRICAS" mm WHERE mm."IMENSAJE" = mo."IMENSAJE"
);

COMMENT ON TABLE "BD_LANGLAB"."CONVERSACION_MENSAJE" IS 'Mensajes de conversación (input/output).';
COMMENT ON TABLE "BD_LANGLAB"."CONVERSACION_MENSAJE_METRICAS" IS 'Métricas por mensaje: tokens, latencia, calificación, meta LangGraph.';
