-- Roles y reglas allow por endpoint (METHOD:path). Usuario → rol en AUTH_USER.ROLECODE.
CREATE SCHEMA IF NOT EXISTS "BD_LANGLAB";

ALTER TABLE "BD_LANGLAB"."AUTH_USER" ADD COLUMN IF NOT EXISTS "ROLECODE" TEXT;

CREATE TABLE IF NOT EXISTS "BD_LANGLAB"."AUTH_ROLE" (
	"ROLECODE" TEXT PRIMARY KEY,
	"DESCRIPTION" TEXT,
	"ACTIVE" BOOLEAN NOT NULL DEFAULT true,
	"FHCRE" TIMESTAMPTZ NOT NULL DEFAULT now(),
	"FHULTACT" TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "BD_LANGLAB"."AUTH_ROLEALLOW" (
	"ROLECODE" TEXT NOT NULL REFERENCES "BD_LANGLAB"."AUTH_ROLE" ("ROLECODE") ON DELETE CASCADE,
	"ALLOWRULE" TEXT NOT NULL,
	PRIMARY KEY ("ROLECODE", "ALLOWRULE")
);
