-- Consolida TDCONSULTA + TDCONSULTA_INSTRUCCION + TDCONSULTA_CORPUS
-- → BD_LANGLAB.CONVERSACION_TIPOCONSULTA (dominio conversación).

CREATE TABLE IF NOT EXISTS "BD_LANGLAB"."CONVERSACION_TIPOCONSULTA" (
	"ITIPOCONSULTA" TEXT PRIMARY KEY,
	"NCONSULTA" TEXT NOT NULL DEFAULT '',
	"DESCRIPCION" TEXT NOT NULL DEFAULT '',
	"BACTIVO" BOOLEAN NOT NULL DEFAULT TRUE,
	"INSTRUCCIONES" JSONB NOT NULL DEFAULT '[]',
	"CORPUS" JSONB NOT NULL DEFAULT '[]'
);

DO $$
BEGIN
	IF EXISTS (SELECT 1 FROM pg_tables WHERE schemaname = 'BD_LANGLAB' AND tablename = 'TDCONSULTA') THEN
		INSERT INTO "BD_LANGLAB"."CONVERSACION_TIPOCONSULTA" (
			"ITIPOCONSULTA", "NCONSULTA", "DESCRIPCION", "BACTIVO", "INSTRUCCIONES", "CORPUS"
		)
		SELECT
			t."ITDCONSULTA",
			t."NCONSULTA",
			t."DESCRIPCION",
			t."BACTIVO",
			COALESCE((
				SELECT jsonb_agg(
					jsonb_build_object('IINSTRUCCION', i."IINSTRUCCION", 'IORDEN', i."IORDEN")
					ORDER BY i."IORDEN"
				)
				FROM "BD_LANGLAB"."TDCONSULTA_INSTRUCCION" i
				WHERE i."ITDCONSULTA" = t."ITDCONSULTA"
			), '[]'::jsonb),
			COALESCE((
				SELECT jsonb_agg(c."CORPUS" ORDER BY c."IORDEN")
				FROM "BD_LANGLAB"."TDCONSULTA_CORPUS" c
				WHERE c."ITDCONSULTA" = t."ITDCONSULTA"
			), '[]'::jsonb)
		FROM "BD_LANGLAB"."TDCONSULTA" t
		ON CONFLICT ("ITIPOCONSULTA") DO UPDATE SET
			"NCONSULTA" = EXCLUDED."NCONSULTA",
			"DESCRIPCION" = EXCLUDED."DESCRIPCION",
			"BACTIVO" = EXCLUDED."BACTIVO",
			"INSTRUCCIONES" = CASE
				WHEN "BD_LANGLAB"."CONVERSACION_TIPOCONSULTA"."INSTRUCCIONES" = '[]'::jsonb
					THEN EXCLUDED."INSTRUCCIONES"
				ELSE "BD_LANGLAB"."CONVERSACION_TIPOCONSULTA"."INSTRUCCIONES"
			END,
			"CORPUS" = CASE
				WHEN "BD_LANGLAB"."CONVERSACION_TIPOCONSULTA"."CORPUS" = '[]'::jsonb
					THEN EXCLUDED."CORPUS"
				ELSE "BD_LANGLAB"."CONVERSACION_TIPOCONSULTA"."CORPUS"
			END;
	END IF;

	IF EXISTS (SELECT 1 FROM pg_tables WHERE schemaname = 'BD_LANGLAB' AND tablename = 'TDCONSULTA_CORPUS') THEN
		DROP TABLE "BD_LANGLAB"."TDCONSULTA_CORPUS";
	END IF;
	IF EXISTS (SELECT 1 FROM pg_tables WHERE schemaname = 'BD_LANGLAB' AND tablename = 'TDCONSULTA_INSTRUCCION') THEN
		DROP TABLE "BD_LANGLAB"."TDCONSULTA_INSTRUCCION";
	END IF;
	IF EXISTS (SELECT 1 FROM pg_tables WHERE schemaname = 'BD_LANGLAB' AND tablename = 'TDCONSULTA') THEN
		DROP TABLE "BD_LANGLAB"."TDCONSULTA";
	END IF;
END;
$$;

COMMENT ON TABLE "BD_LANGLAB"."CONVERSACION_TIPOCONSULTA" IS
	'Catálogo tipo de consulta (clasificador): metadatos, enlaces INSTRUCCION y corpus RAG.';
