-- Filestore: metadatos de archivos en proveedor externo intercambiable.
-- Las credenciales del proveedor se respaldan en BD_LANGLAB.CREDENCIALES (tabla existente).
CREATE SCHEMA IF NOT EXISTS "BD_LANGLAB";

CREATE TABLE IF NOT EXISTS "BD_LANGLAB"."FILESTORE_FILE" (
	"FILEKEY" TEXT PRIMARY KEY,
	"FILENAME" TEXT NOT NULL,
	"CONTENTTYPE" TEXT,
	"SIZEBYTES" BIGINT,
	"SHA256" TEXT,
	"PROVIDER" TEXT NOT NULL,
	"METADATA" JSONB,
	"FHCRE" TIMESTAMPTZ NOT NULL DEFAULT now(),
	"FHULTACT" TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS "IX_FILESTORE_FILE_FILENAME" ON "BD_LANGLAB"."FILESTORE_FILE" ("FILENAME");
