CREATE SCHEMA IF NOT EXISTS "BD_RAG";

COMMENT ON SCHEMA "BD_RAG" IS 'Corpus vectorizado. BD dedicada RAG_DATABASE_URL.';

CREATE TABLE IF NOT EXISTS "BD_RAG"."INDEX_RUN" (
	iid BIGSERIAL PRIMARY KEY,
	profile TEXT NOT NULL,
	sourcetype TEXT NOT NULL DEFAULT 'unknown',
	sourceid TEXT NOT NULL DEFAULT '',
	chunksadded INT NOT NULL DEFAULT 0,
	startedat TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	finishedat TIMESTAMPTZ,
	meta JSONB NOT NULL DEFAULT '{}'
);

CREATE INDEX IF NOT EXISTS "IX_RAG_INDEX_RUN_PROFILE"
	ON "BD_RAG"."INDEX_RUN" (profile, startedat DESC);

CREATE TABLE IF NOT EXISTS "BD_RAG"."VECTOR_CONTAPYME" (
	id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
	content TEXT,
	metadata JSONB,
	embedding vector(384)
);

CREATE INDEX IF NOT EXISTS "IX_RAG_VEC_CONTAPYME_EMBEDDING"
	ON "BD_RAG"."VECTOR_CONTAPYME" USING hnsw (embedding vector_cosine_ops);
