DROP TABLE IF EXISTS "BD_RAG"."VECTOR_FITDOCS" CASCADE;
DROP TABLE IF EXISTS "BD_RAG"."RAG_VECFITDOCS" CASCADE;
DROP TABLE IF EXISTS "BD_RAG"."VECTOR_VECFITDOCS" CASCADE;
DROP TABLE IF EXISTS "BD_RAG"."rag_vec_fitdocs" CASCADE;

DROP SCHEMA IF EXISTS bd_rag CASCADE;
