/** Funciones SQL en BD_LANGLAB (nomenclatura post-migración entidad). */
export const FN_CONVERSACION_NEXT_TURN_INDEX = '"BD_LANGLAB"."CONVERSACION_NEXTTURNINDEX"';
export const FN_ORCHESTRATOR_EXPIRE_STALE_LEASES = '"BD_LANGLAB"."ORCHESTRATOR_EXPIRESTALORCHESTRATORLEASES"';
